import { createContext, useContext, useState, useEffect } from 'react'

const TRANSLATIONS = {
  en: {
    // ── Nav ──────────────────────────────────────────────────────────────
    home: 'Home',
    chat: 'Chat',
    cabinet: 'Cabinet',
    profile: 'Profile',
    history: 'History',
    schedule: 'Schedule',
    stackBuilder: 'Stack Builder',
    doctorPrep: 'Doctor Prep',
    sideEffects: 'Side Effects',
    journal: 'Journal',
    progress: 'Progress',
    goals: 'Goals',
    notifications: 'Notifications',
    nutrition: 'Nutrition',
    foodDb: 'Food DB',
    exercise: 'Exercise',
    logActivity: 'Log Activity',
    noWorkoutsYet: 'No workouts logged yet',
    logFirstActivity: 'Log your first activity',
    activityType: 'Activity Type',
    intensityEasy: 'Easy',
    intensityModerate: 'Moderate',
    intensityHard: 'Intense',
    addExercise: '+ Add Exercise',
    saveSession: 'Save Session',
    exerciseAiPlaceholder: 'Describe your workout… e.g. "Bench press 3x10 80kg, gym 60 mins" or "跑咗5公里，45分鐘"',
    parseWithAI: 'Parse with AI',
    parsing: 'Parsing...',
    parsedPreview: 'Parsed result',
    editManually: 'Edit',
    fillManually: 'Fill manually',
    thisWeek: 'This week',
    lastWeek: 'Last week',
    // ── Exercise activity types ──────────────────────────────────────────
    activityGym: 'Gym',
    activityRunning: 'Running',
    activitySwimming: 'Swimming',
    activityBasketball: 'Basketball',
    activityBadminton: 'Badminton',
    activityCycling: 'Cycling',
    activityYoga: 'Yoga',
    activityHiking: 'Hiking',
    activityOther: 'Other',
    // ── ExerciseNew form ─────────────────────────────────────────────────
    date: 'Date',
    startTraining: 'Start Training',
    noPlanExercises: 'This plan has no specific exercises. Add manually.',
    exTypeStrength: 'Strength',
    exTypeBodyweight: 'Bodyweight',
    exTypeTimed: 'Timed',
    exTypeCardio: 'Cardio',
    exTypeSession: 'Session',
    // ── Exercise list page ───────────────────────────────────────────────
    filterAll: 'All',
    weekSessions: 'sessions',
    weekMinutes: 'min this week',
    noSessionsForFilter: 'No sessions for this activity type.',
    logFirstActivityHint: 'Start logging to track your progress.',
    // ── Exercise detail page ─────────────────────────────────────────────
    duration: 'Duration',
    distance: 'Distance',
    exercises: 'Exercises',
    notes: 'Notes',
    editSession: 'Edit Session',
    save: 'Save',
    saving: 'Saving...',
    deleteSession: 'Delete Session',
    deleteSessionConfirm: 'This session will be permanently removed.',
    deleteConfirmBtn: 'Delete',
    deleting: 'Deleting...',
    cancel: 'Cancel',
    back: 'Back',
    freePlan: 'Free plan',
    menu: 'Menu',
    signOut: 'Sign out',
    // ── Greetings ────────────────────────────────────────────────────────
    goodMorning: 'Good morning',
    goodAfternoon: 'Good afternoon',
    goodEvening: 'Good evening',
    // ── Home screen ──────────────────────────────────────────────────────
    locale: 'en-GB',
    statsSupplements: 'Supplements',
    statsConflicts: 'Conflicts',
    statsStreak: 'Streak',
    statsPowered: 'Powered',
    todaySchedule: "Today's schedule",
    noScheduleYet: 'No schedule yet.',
    addSuppsForSchedule: 'Add supplements to see your schedule',
    askAI: 'Ask Recallth AI',
    askAISubtitle: 'I remember your full health profile',
    askPlaceholder: 'Ask about supplements, dosing, interactions…',
    quickPrompt1: 'Should I take D3 with food?',
    quickPrompt2: 'Check my interactions',
    quickPrompt3: 'Best time for magnesium?',
    recentConversations: 'Recent conversations',
    noConversationsYet: 'No conversations yet.',
    startFirstChat: 'Start your first chat',
    conversationFallback: 'Conversation',
    viewAllConversations: 'View all conversations →',
    // ── Cabinet screen ───────────────────────────────────────────────────
    cabinetTitle: 'Cabinet',
    addSupplement: 'Add supplement',
    searchPlaceholder: 'Search supplements...',
    cabinetEmpty: 'Your cabinet is empty.',
    cabinetEmptySub: 'Add your first supplement.',
    noResults: 'No supplements match your search.',
    cabinetNotInCabinet: 'Not in your cabinet',
    isThisTheOne: 'Is this the one?',
    notThisOne: "Not this one — add manually",
    aiLookupNoMatch: 'No match found — add it manually.',
    recent: 'Recent',
    interactionWarning: (n) => `${n} interaction${n !== 1 ? 's' : ''} detected in your cabinet`,
    // ── Cabinet Add ──────────────────────────────────────────────────────
    addTitle: 'Add Supplement',
    addSubtitle: 'Track a new item',
    addButton: 'Add to cabinet',
    adding: 'Adding...',
    // ── Cabinet Detail ───────────────────────────────────────────────────
    editButton: 'Edit',
    saveButton: 'Save',
    saving: 'Saving...',
    cancelButton: 'Cancel',
    deleteButton: 'Delete supplement',
    deleting: 'Deleting...',
    confirmDelete: 'Delete this supplement?',
    cannotUndo: 'This action cannot be undone.',
    // ── Form field labels ────────────────────────────────────────────────
    fieldName: 'Name',
    fieldType: 'Type',
    fieldDosage: 'Dosage',
    fieldFrequency: 'Frequency',
    fieldTiming: 'Timing',
    fieldBrand: 'Brand (optional)',
    fieldNotes: 'Notes (optional)',
    fieldDescription: 'Description',
    fieldIngredients: 'Ingredients',
    uploadPhoto: 'Upload photo',
    changePhoto: 'Change photo',
    uploading: 'Uploading...',
    imageTooLarge: 'Image must be under 2MB',
    aiLookupButton: 'AI Auto-fill product info',
    aiLookupTitle: 'AI Product Lookup',
    aiLookupHint: 'Type a product name (e.g. "PVL Whey Gold chocolate") and AI will fill in all the details.',
    aiLookupPlaceholder: 'e.g. NOW Foods Magnesium 400mg',
    aiLookupSearch: 'Search',
    aiLookupSearching: 'Searching...',
    aiLookupClear: 'Clear',
    aiLookupConfirmTitle: 'Is this the right product?',
    aiLookupConfirm: 'Yes, fill it in',
    aiLookupRetry: 'Try again',
    aiLookupFilled: 'Product info filled by AI',
    aiLookupUndo: 'Undo',
    // ── History screen ───────────────────────────────────────────────────
    historyTitle: 'History',
    historySub: (n) => `${n} conversation${n !== 1 ? 's' : ''}`,
    noConversationsTitle: 'No conversations yet',
    startConversation: 'Start a conversation',
    noConversationsMatch: 'No conversations match your search.',
    searchConversations: 'Search conversations...',
    // ── Chat ─────────────────────────────────────────────────────────────
    chatGreeting: (name) => `${name} 👋`,
    goodMorningGreet: 'Good morning',
    newChat: 'New chat',
    tapSuggestion: 'Tap a suggestion or ask anything...',
    stackReview: 'Stack review',
    todayPlan: "Today's plan",
    chatTitle: 'Recallth AI',
    chatHeaderActive: 'Chat',
    chatHowCanHelp: 'How can I help with your stack today?',
    chatSugg1: 'My stack today',
    chatSugg2: 'Interactions?',
    chatSugg3: 'Best timing',
    chatSugg4: 'Pre-workout plan',
    chatSugg5: 'Sleep supplements',
    chatSugg6: 'Evidence check',
    chatRecent: 'Recent',
    chatViewAll: 'View all',
    chatConversations: 'Conversations',
    chatSearch: 'Search...',
    chatNoConvos: 'No conversations yet',
    chatNoMatches: 'No matches',
    chatFollowUp: 'Follow up...',
    chatAskAnything: 'Ask anything about your supplements...',
    chatExerciseContextPlaceholder: 'Ask about this workout session...',
    chatHistory: 'Conversations',
    chatNoHistory: 'No past conversations yet.',
    chatUntitled: 'Untitled conversation',
    chatSentImage: 'Sent an image',
    chatImagePrompt: 'What is this supplement?',
    chatNoResponse: 'No response',
    chatError: 'Something went wrong. Please try again.',
    chatRetry: 'Retry',
    chatQuickActions: 'Quick actions',
    chatJustNow: 'Just now',
    chatYesterday: 'Yesterday',
    // ── Profile ──────────────────────────────────────────────────────────
    aboutMe: 'About me',
    goalsSection: 'Goals',
    exerciseSection: 'Exercise',
    dietSection: 'Diet',
    sleepSection: 'Sleep',
    lifestyleSection: 'Lifestyle',
    sportsSection: 'Sports & Training',
    conditionsSection: 'Conditions & Injuries',
    weakAreas: 'Weak areas:',
    notSet: 'Not set',
    updatedViaChat: 'Updated via chat',
    addedViaChat: 'Added via chat',
    daysAgo: 'days ago',
    sportStatusActive: 'active',
    sportStatusLearning: 'learning',
    sportStatusPast: 'past',
    injuryStatusActive: 'active',
    injuryStatusRecovered: 'recovered',
    profileCompletenessLabel: 'Your profile is building',
    profileCompleteTellMe: 'Tell me about your',
    promptCheckStack: 'Check my stack',
    promptCheckStackDesc: 'Do any of my supplements interact?',
    promptUpdateHealth: 'Update my health',
    promptUpdateHealthDesc: "I've been sleeping only 4-5 hours",
    promptPeriodicReview: 'Periodic review',
    promptPeriodicReviewDesc: 'You mentioned wrist pain 2 months ago — still hurting?',
    whatCanIHelp: 'What can I help with?',
    missingFromProfile: 'Missing from your profile',
    tellMeAboutSleep: 'Tell me about your sleep',
    anyDietaryRestrictions: 'Any dietary restrictions?',
    tellMeAboutExercise: 'Tell me about your exercise routine',
    tellMeAboutGoals: 'What are your health goals?',
    tellMeAboutLifestyle: 'Tell me about your lifestyle',
    tellMeAboutSports: 'What sports do you play?',
    tellMeAboutInjuries: 'Any injuries or conditions?',
    savingEllipsis: 'Saving…',
    failedToSave: 'Failed to save — try again',
    profileHistory: 'History',
    profileSchedule: 'Schedule',
    profileDashboard: 'Dashboard',
    fieldAge: 'Age',
    fieldHeight: 'Height',
    fieldWeight: 'Weight',
    fieldGender: 'Gender',
    fieldPrimaryGoal: 'Primary goal',
    fieldGoalsList: 'Goals (comma separated)',
    fieldFitnessLevel: 'Fitness level',
    fieldRestrictions: 'Restrictions (comma separated)',
    fieldAllergies: 'Allergies (comma separated)',
    fieldHoursPerNight: 'Hours per night',
    fieldIssues: 'Issues (comma separated)',
    fieldStressLevel: 'Stress level',
    fieldSmokingStatus: 'Smoking status',
    fieldAlcohol: 'Alcohol consumption',
    language: 'Language',
    logOut: 'Log out',
    // ── Profile security ─────────────────────────────────────────────────
    securitySection: 'Security',
    securityPassword: 'Password',
    securityPasswordSet: 'Password set',
    securityGoogleLinked: 'Google linked',
    securitySetPassword: 'Set a password',
    securitySetPasswordSub: 'Add a password so you can also sign in with email.',
    securityNewPassword: 'New password',
    securityPasswordHint: 'Min. 8 characters',
    securityConfirmPassword: 'Confirm password',
    securityRepeatPassword: 'Repeat password',
    securityPasswordTooShort: 'Password must be at least 8 characters.',
    securityPasswordMismatch: 'Passwords do not match.',
    securityPasswordFailed: 'Failed to set password.',
    securityLinkGoogle: 'Link Google account',
    securityLinkGoogleSub: 'Sign in faster with Google on this device.',
    securityLinking: 'Linking…',
    securityGoogleNotConfigured: 'Google Sign-In is not configured.',
    fieldActivityLevel: 'Activity level',
    // ── Goals screen ─────────────────────────────────────────────────────
    goalsSubtitle: 'Track your weekly wellbeing goals',
    goalsLogTitle: 'Log this week',
    goalsNameLabel: 'Goal name',
    goalsNamePlaceholder: 'e.g. Better sleep, More energy',
    goalsRatingLabel: 'How did it go?',
    goalsSubmit: 'Log this week',
    goalsSubmitting: 'Logging…',
    goalsNudgeTitle: 'AI insight',
    goalsEmpty: 'Log your first weekly check-in above to start tracking',
    goalsEmptyTitle: 'No goals tracked yet',
    goalsTrend: 'vs last week',
    goalsWeeks: 'Last 8 weeks',
    goalsNameRequired: 'Please enter a goal name',
    goalsRatingRequired: 'Please select a rating',
    goalsSubmitError: 'Failed to log — please try again',
    // ── Goals screen redesign ────────────────────────────────────────────
    goalsPageTitle: 'Goals',
    goalsPageSubtitle: 'Your health goals shape your supplement recommendations',
    goalsNoGoals: 'No goals set yet',
    goalsNoGoalsHint: 'Add a goal below to get personalised supplement recommendations',
    goalsAddSectionHeader: 'Add a goal',
    goalsInputPlaceholder: 'e.g. I want to build muscle and improve my sleep...',
    goalsInterpretBtn: 'Interpret with AI',
    goalsInterpreting: 'Interpreting…',
    goalsInterpretedTitle: 'I understood these goals:',
    goalsConfirmBtn: 'Add to my goals',
    goalsTryAgainBtn: 'Try again',
    goalsSaving: 'Saving…',
    goalsRecommendationsCta: 'Get supplement recommendations based on your goals →',
    goalsDeleteError: 'Failed to remove goal',
    goalsSaveError: 'Failed to save goals',
    goalsAddNote: 'Add a note',
    goalsNotePlaceholder: 'e.g. Target: gain 5kg muscle in 6 months...',
    goalsSaveNote: 'Save',
    goalsCancelNote: 'Cancel',
    goalsSavingNote: 'Saving…',
    goalsSeeInsights: 'See supplement insights',
    goalsInsightsLoading: 'Analysing your stack…',
    goalsInsightsSupporting: 'Supporting your goal',
    goalsInsightsMissing: 'Consider adding',
    goalsInsightsSummary: 'AI summary',
    goalsInsightsNoneSupporting: 'None of your current supplements directly target this goal.',
    goalsInsightsError: 'Could not load insights. Try again.',
    goalsAddToCabinet: '+ Cabinet',
    // ── Auth ────────────────────────────────────────────────────────────
    authWelcome: 'Welcome back',
    authGetStarted: 'Get started',
    authSignInSub: 'Sign in to your account',
    authCreateSub: 'Create your free account',
    authSignUp: 'Sign up',
    authLogIn: 'Log in',
    authContinueGoogle: 'Continue with Google',
    authComingSoon: 'Coming soon',
    authOr: 'or',
    authName: 'Name',
    authNamePlaceholder: 'Your name',
    authEmail: 'Email',
    authEmailPlaceholder: 'you@example.com',
    authPassword: 'Password',
    authPasswordPlaceholder: 'Min. 8 characters',
    authPasswordPlaceholderLogin: 'Your password',
    authPleaseWait: 'Please wait…',
    authCreateAccount: 'Create account',
    authNoAccount: "Don't have an account? ",
    authHaveAccount: 'Already have an account? ',
    // ── Schedule screen ─────────────────────────────────────────────────
    scheduleTitle: 'Schedule',
    scheduleEmpty: 'No schedule yet',
    scheduleEmptySub: 'Add supplements to your cabinet to generate a schedule',
    scheduleGoToCabinet: 'Go to Cabinet',
    slotMorning: 'Morning',
    slotAfternoon: 'Afternoon',
    slotEvening: 'Evening',
    slotNight: 'Night',
    slotAnytime: 'Anytime',
    // ── Journal ─────────────────────────────────────────────────────────
    journalTitle: 'Journal',
    journalSub: 'Track how you feel each day',
    journalLogToday: 'Log today',
    journalMood: 'Mood',
    journalEnergy: 'Energy',
    journalNotesPlaceholder: 'How are you feeling?',
    journalSubmit: 'Log Entry',
    journalSave: 'Save',
    journalNoEntries: 'No entries yet',
    journalNoEntriesSub: 'Log your first entry above to get started',
    journalDeleteConfirm: 'Delete this entry?',
    journalDelete: 'Delete',
    // ── Side Effects ────────────────────────────────────────────────────
    sideEffectsTitle: 'Side Effects',
    sideEffectsSub: 'Track how supplements affect you over time',
    sideEffectsLog: 'Log a side effect',
    sideEffectsSupplement: 'Supplement',
    sideEffectsSelectSupp: 'Select supplement…',
    sideEffectsSuppPlaceholder: 'Supplement name',
    sideEffectsWhat: 'What did you notice?',
    sideEffectsWhatPlaceholder: 'What did you notice?',
    sideEffectsSeverity: 'Severity',
    sideEffectsMild: 'Mild',
    sideEffectsModerate: 'Moderate',
    sideEffectsSevere: 'Severe',
    sideEffectsDate: 'Date',
    sideEffectsSubmit: 'Log Effect',
    sideEffectsLogging: 'Logging…',
    sideEffectsHistory: 'History',
    sideEffectsEmpty: 'No side effects logged — track how supplements affect you',
    sideEffectsEmptyTitle: 'No side effects yet',
    sideEffectsToday: 'Today',
    sideEffectsDeleteConfirm: 'Are you sure?',
    sideEffectsYes: 'Yes',
    sideEffectsNo: 'No',
    // ── Progress ────────────────────────────────────────────────────────
    progressTitle: 'Progress',
    progressSub: 'Track your body stats over time',
    progressLogStats: 'Log Stats',
    progressWeight: 'Weight (kg)',
    progressBodyFat: 'Body fat %',
    progressDate: 'Date',
    progressNotes: 'Notes',
    progressOptional: 'optional',
    progressLogging: 'Logging…',
    progressWeightPlaceholder: 'e.g. 72.5',
    progressKgNow: 'kg now',
    progressChange: 'change',
    progressEntries: 'entries',
    progressWeightTrend: 'Weight trend (kg)',
    progressBfTrend: 'Body fat trend (%)',
    progressAllEntries: 'All entries',
    progressEmpty: 'No stats yet — log your first measurement',
    progressEmptySub: 'Use the form above to get started.',
    progressBodyFatLabel: '% body fat',
    progressWeightRequired: 'Weight is required.',
    progressFailed: 'Failed to log stats — try again.',
    // ── Bloodwork ───────────────────────────────────────────────────────
    bloodworkTitle: 'Bloodwork',
    bloodworkSub: 'Track your lab results over time',
    bloodworkLogNew: 'Log new results',
    bloodworkTestDate: 'Test date',
    bloodworkQuickAdd: 'Quick add',
    bloodworkCustomMarker: 'Custom marker',
    bloodworkUnit: 'Unit',
    bloodworkAdd: 'Add',
    bloodworkValue: 'Value',
    bloodworkSaving: 'Saving…',
    bloodworkLogResults: 'Log Results',
    bloodworkAnalysing: 'Analysing…',
    bloodworkGetAI: 'Get AI interpretation',
    bloodworkInterpretFailed: 'Interpretation failed — try again',
    bloodworkEmpty: 'No bloodwork logged',
    bloodworkEmptySub: 'Add markers above to track your lab results',
    bloodworkInRange: 'In range',
    bloodworkBelow: 'Below range',
    bloodworkAbove: 'Above range',
    bloodworkMarker: 'marker',
    bloodworkMarkers: 'markers',
    // ── Doctor Prep ─────────────────────────────────────────────────────
    doctorPrepTitle: 'Doctor Prep',
    doctorPrepSub: 'Questions to ask at your next appointment',
    doctorPrepGenerating: 'Generating your questions…',
    doctorPrepFailed: "Couldn't generate questions",
    doctorPrepFailedSub: 'Make sure your cabinet and profile have some data, then try again.',
    doctorPrepRetry: 'Retry',
    doctorPrepReady: (n) => `${n} question${n !== 1 ? 's' : ''} ready`,
    doctorPrepCopied: 'Copied!',
    doctorPrepCopyAll: 'Copy all',
    doctorPrepNoCabinet: 'Your cabinet is empty',
    doctorPrepNoCabinetSub: 'Add supplements to your cabinet first so we can generate personalised questions for your doctor.',
    // ── Stack Builder ───────────────────────────────────────────────────
    stackBuilderTitle: 'Stack Builder',
    stackBuilderSub: 'Enter a health goal and get personalised supplement recommendations in seconds.',
    stackBuilderPlaceholder: 'e.g. better sleep, muscle building…',
    stackBuilderGenerate: 'Build Stack',
    stackBuilderGenerating: 'Generating…',
    stackBuilderEmpty: 'Build your personalised stack',
    stackBuilderEmptySub: "Type a health goal above — sleep, energy, performance, immunity — and we'll recommend the right supplements for you.",
    stackBuilderLoading: 'Generating your stack…',
    stackBuilderFailed: "Couldn't generate recommendations — try again",
    stackBuilderRetry: 'Retry',
    stackBuilderInStack: 'In your stack',
    stackBuilderAdded: 'Added',
    stackBuilderAddToStack: 'Add to stack',
    stackBuilderAdding: 'Adding…',
    stackBuilderEssential: 'Essential',
    stackBuilderBeneficial: 'Beneficial',
    stackBuilderOptional: 'Optional',
    stackBuilderExGoal1: 'Better sleep',
    stackBuilderExGoal2: 'Muscle building',
    stackBuilderExGoal3: 'More energy',
    stackBuilderSavedGoalsLabel: 'Your saved goals',
    stackBuilderOrType: 'Or enter a new goal',
    // ── Notifications ───────────────────────────────────────────────────
    notificationsTitle: 'Notifications',
    notificationsSub: 'Manage reminders, digests and your timezone.',
    notificationsLoadError: 'Could not load settings — try refreshing',
    notificationsReminders: 'Daily supplement reminders',
    notificationsNoReminders: 'No reminders set. Add one below.',
    notificationsAddReminder: 'Add reminder',
    notificationsDigestTitle: 'Weekly digest email',
    notificationsDigestToggle: 'Email digest',
    notificationsDigestSub: 'Receive a weekly summary of your supplement activity',
    notificationsDigestDay: 'Send on',
    notificationsTimezone: 'Timezone',
    notificationsSaved: 'Saved',
    notificationsMon: 'Mon',
    notificationsTue: 'Tue',
    notificationsWed: 'Wed',
    notificationsThu: 'Thu',
    notificationsFri: 'Fri',
    notificationsSat: 'Sat',
    notificationsSun: 'Sun',
    // ── Onboarding ──────────────────────────────────────────────────────
    onboardingStep: (curr, total) => `Step ${curr} of ${total}`,
    onboardingGoalsTitle: 'What are your goals?',
    onboardingGoalsSub: 'Select all that apply',
    onboardingGoalMuscle: 'Muscle & strength',
    onboardingGoalRecovery: 'Recovery',
    onboardingGoalSleep: 'Better sleep',
    onboardingGoalEnergy: 'More energy',
    onboardingGoalHealth: 'General health',
    onboardingGoalWeight: 'Weight management',
    onboardingContinue: 'Continue',
    onboardingBack: 'Back',
    onboardingSuppTitle: 'Add your first supplement',
    onboardingSuppSub: 'You can add more from your cabinet later',
    onboardingSuppName: 'Supplement name',
    onboardingSuppNamePlaceholder: 'e.g. Creatine, Omega-3, Vitamin D',
    onboardingSuppDose: 'Dose',
    onboardingSuppDosePlaceholder: 'e.g. 5g, 1000mg, 2 capsules',
    onboardingSuppTiming: 'Timing',
    onboardingSuppSkip: 'Skip for now',
    onboardingSchedTitle: 'When do you prefer to dose?',
    onboardingSchedSub: 'We will optimise your schedule around this',
    onboardingSchedMorning: 'Morning-heavy',
    onboardingSchedMorningSub: 'Front-load your supplements before midday',
    onboardingSchedEvening: 'Evening-heavy',
    onboardingSchedEveningSub: 'Take most supplements in the afternoon and evening',
    onboardingFinish: 'Finish setup',
    // ── Evidence ────────────────────────────────────────────────────────
    evidenceStrong: 'Strong evidence',
    evidenceGood: 'Good evidence',
    evidenceModerate: 'Moderate evidence',
    evidenceLimited: 'Limited evidence',
    // ── Misc ────────────────────────────────────────────────────────────
    active: 'Active',
    conflicts: 'Conflicts',
    interactions: 'Interactions',
    failedToLoad: 'Failed to load',
    suppNotFound: 'Supplement not found',
    nameRequired: 'Name is required',
    dosageRequired: 'Dosage is required',
    failedToSaveChanges: 'Failed to save changes',
    failedToDelete: 'Failed to delete',
    failedToAdd: 'Failed to add supplement',
    failedToLoadHistory: 'Failed to load history',
    imageAttached: 'Image attached',
    searchEllipsis: 'Search or ask anything…',
    msgs: 'msgs',
    messages: 'messages',
    unknown: 'Unknown',
    supplement: 'Supplement',
    // ── Relative time ───────────────────────────────────────────────────
    timeMinAgo: (n) => `${n}m ago`,
    timeHrAgo: (n) => `${n}h ago`,
    timeDaysAgo: (n) => `${n}d ago`,
    timeYesterday: 'Yesterday',
    // ── Nutrition Tracker ────────────────────────────────────────────────
    nutritionTitle: 'Nutrition Tracker',
    nutritionSub: 'Track your daily nutrients',
    nutritionCategoryGym: 'Gym & Muscle',
    nutritionCategoryWeightLoss: 'Weight Loss',
    nutritionCategoryDiabetes: 'Diabetes',
    nutritionCategoryKidney: 'Kidney Health',
    nutritionCategoryPregnancy: 'Pregnancy',
    nutritionCategoryCustom: 'Custom',
    nutritionCalories: 'Calories',
    nutritionProtein: 'Protein',
    nutritionCarbs: 'Carbs',
    nutritionFat: 'Fat',
    nutritionFiber: 'Fiber',
    nutritionSodium: 'Sodium',
    nutritionSugar: 'Sugar',
    nutritionFolate: 'Folate',
    nutritionIron: 'Iron',
    nutritionMealBreakfast: 'Breakfast',
    nutritionMealLunch: 'Lunch',
    nutritionMealDinner: 'Dinner',
    nutritionMealSnack: 'Snack',
    nutritionAiPlaceholder: 'e.g. "Had a chicken sandwich and a latte for lunch"\n"Breakfast: 2 scrambled eggs, toast, OJ"\n"Just a few bites of fried rice"',
    nutritionAiParsing: 'Analysing...',
    nutritionAiParsed: 'Found {n} foods',
    nutritionConfirm: 'Add to log',
    nutritionTotal: 'Total',
    nutritionAddFood: 'Add Food',
    nutritionAddTitle: 'Log Food',
    nutritionFieldFood: 'Food name',
    nutritionFieldQuantity: 'Quantity',
    nutritionFieldMeal: 'Meal',
    nutritionEmpty: 'No entries yet',
    nutritionEmptySub: 'Log your first meal',
    nutritionDeleteConfirm: 'Delete this entry?',
    nutritionDisclaimer: 'This is not medical advice. Consult your doctor for personalised guidance.',
    nutritionAlgoTitle: 'How are targets calculated?',
    nutritionAlgoPersonalised: 'Personalised · Mifflin-St Jeor',
    nutritionAlgoUpdateProfile: 'Update your profile to recalculate.',
    nutritionAlgoDefault: 'Targets are using general guidelines.',
    nutritionAlgoDefaultSub: 'Complete your profile — height, weight, age, sex, and activity level — to get targets personalised to your body using the Mifflin-St Jeor formula.',
    nutritionAlgoCompleteProfile: 'Complete profile →',
    nutritionTabAI: 'AI Analyser',
    nutritionTabManual: 'Manual Entry',
    nutritionAiAnalyse: 'Analyse',
    nutritionAdding: 'Adding…',
    nutritionManualNamePlaceholder: 'Food name (e.g. 白飯, Salad)',
    nutritionManualQtyPlaceholder: 'Qty',
    nutritionManualUnitPlaceholder: 'Unit (e.g. 碗, g, cup)',
    nutritionManualAdd: 'Add to log',
    nutritionManualSaving: 'Saving…',
    nutritionChooseDrink: 'Choose your drink',
    nutritionNoFoodDetails: 'No food details available',
    nutritionDeleteRecord: 'Delete record',
    nutritionDeleteEntry: 'Delete this entry?',
    nutritionCalHasRecord: 'Has record',
    nutritionCalToday: 'Today',
    nutritionEntryDeleted: 'Entry deleted',
    nutritionUndo: 'Undo',
    nutritionDragHandle: 'Drag to move',
    nutritionMoveToDate: 'Move to date',
    nutritionMoveConfirm: 'Move',
    nutritionMoveBack: '← Back',
    nutritionCustomiseBtn: 'Customise',
    nutritionCustomiseTitle: 'Customise Nutrients',
    nutritionCustomiseSave: 'Save',
    nutritionCustomiseGoalPlaceholder: 'Goal',
    nutritionSelectMode: 'Select',
    nutritionSelectCancel: 'Cancel',
    nutritionSelectAll: 'All',
    nutritionBatchDelete: 'Delete ({n})',
    nutritionBatchConfirmTitle: 'Delete {n} item(s)?',
    nutritionBatchConfirmSub: 'This cannot be undone.',
    nutritionBatchDeleting: 'Deleting…',
    // ── Food Database ─────────────────────────────────────────────────────
    foodDbTitle: 'Food Database',
    foodDbSearchPlaceholder: 'Search food name (English or Chinese)…',
    foodDbCommonFoods: 'Common HK Foods',
    foodDbResultsCount: '{n} results',
    foodDbEmpty: 'No foods found',
    foodDbEmptySub: 'Try a different search term',
    foodDbCategoryAll: 'All',
    foodDbCategoryRiceNoodles: 'Rice & Noodles',
    foodDbCategoryProtein: 'Protein',
    foodDbCategoryDimSum: 'Dim Sum',
    foodDbCategorySoup: 'Soup',
    foodDbCategoryBreadPastry: 'Bread & Pastry',
    foodDbCategoryDrinks: 'Drinks',
    foodDbCategoryDesserts: 'Desserts',
    foodDbCategorySnacks: 'Snacks',
    foodDbCategoryFastFood: 'Fast Food',
    foodDbCategoryWholeFood: 'Whole Food',
    foodDbCategoryPackaged: 'Packaged',
    foodDbFlagHighProtein: 'High Protein',
    foodDbFlagHighFiber: 'High Fibre',
    foodDbFlagLowSugar: 'Low Sugar',
    foodDbFlagLowSodium: 'Low Sodium',
    foodDbFlagLowCalorie: 'Low Cal',
    foodDbFlagHighCalorie: 'High Cal',
    foodDbPerServing: 'Per serving',
    foodDbServings: 'Servings',
    foodDbAdd: 'Add to log',
    // ── Common ───────────────────────────────────────────────────────────
    back: 'Back',
    // ── Frequency / Timing options ───────────────────────────────────────
    freqDaily: 'Daily',
    freqTwiceDaily: 'Twice daily',
    freqAsNeeded: 'As needed',
    timingMorning: 'Morning',
    timingPreWorkout: 'Pre-workout',
    timingWithMeals: 'With meals',
    timingEvening: 'Evening',
    timingBeforeBed: 'Before bed',
    // ── Nutrition label scan ─────────────────────────────────────────────
    nutritionSaved: 'Saved',
    nutritionUploadLabelPhoto: 'Upload nutrition label photo',
    nutritionTapToSelectPhoto: 'Tap to select a photo from your device',
    nutritionReadingLabel: 'Reading nutrition label...',
    nutritionTryAgain: 'Try again',
    nutritionExtractedFromPhoto: 'Extracted from photo',
    nutritionUseThis: 'Use this',
    nutritionRetake: 'Retake',
    // ── Nutrition calendar strip ─────────────────────────────────────────
    nutritionGoToToday: 'Today',
    nutritionViewMonth: 'View month',
    nutritionCollapse: 'Collapse',
    // ── Goal mode ────────────────────────────────────────────────────────
    nutritionGoalMode: 'Goal Mode',
    nutritionDidYouMean: 'Did you mean?',
    nutritionRecTitle: 'Supplement Recommendations',
    nutritionRecAllGood: 'Your supplements are covering all nutritional gaps today.',
  },

  'zh-TW': {
    home: '主頁',
    chat: '對話',
    cabinet: '藥箱',
    profile: '個人',
    history: '歷史記錄',
    schedule: '排程',
    stackBuilder: '堆疊配方',
    doctorPrep: '醫師準備',
    sideEffects: '副作用',
    journal: '日誌',
    progress: '進度',
    goals: '目標',
    notifications: '通知設定',
    nutrition: '營養追蹤',
    foodDb: '食物資料庫',
    exercise: '運動',
    logActivity: '記錄運動',
    noWorkoutsYet: '未有運動紀錄',
    logFirstActivity: '記錄你的第一次運動',
    activityType: '運動類型',
    intensityEasy: '輕鬆',
    intensityModerate: '中等',
    intensityHard: '高強度',
    addExercise: '+ 加動作',
    saveSession: '儲存',
    exerciseAiPlaceholder: '描述你的運動…例如「bench press 3組10下80kg，gym 60分鐘」或「跑咗5公里，45分鐘」',
    parseWithAI: 'AI 解析',
    parsing: '解析中...',
    parsedPreview: '解析結果',
    editManually: '手動修改',
    fillManually: '手動填寫',
    thisWeek: '本週',
    lastWeek: '上週',
    activityGym: '健身室',
    activityRunning: '跑步',
    activitySwimming: '游泳',
    activityBasketball: '籃球',
    activityBadminton: '羽毛球',
    activityCycling: '單車',
    activityYoga: '瑜伽',
    activityHiking: '行山',
    activityOther: '其他',
    date: '日期',
    startTraining: '開始訓練',
    noPlanExercises: '此計劃未包含具體動作，可手動加入',
    exTypeStrength: '重訓',
    exTypeBodyweight: '自重',
    exTypeTimed: '計時',
    exTypeCardio: '有氧',
    exTypeSession: '整體',
    filterAll: '全部',
    weekSessions: '次運動',
    weekMinutes: '分鐘（本週）',
    noSessionsForFilter: '此類型未有運動紀錄。',
    logFirstActivityHint: '開始記錄，追蹤你的進度。',
    duration: '時間',
    distance: '距離',
    exercises: '動作',
    notes: '備註',
    editSession: '編輯紀錄',
    save: '儲存',
    saving: '儲存中...',
    deleteSession: '刪除紀錄',
    deleteSessionConfirm: '此運動紀錄將被永久刪除。',
    deleteConfirmBtn: '刪除',
    deleting: '刪除中...',
    cancel: '取消',
    back: '返回',
    freePlan: '免費方案',
    menu: '選單',
    signOut: '登出',
    goodMorning: '早安',
    goodAfternoon: '午安',
    goodEvening: '晚安',
    locale: 'zh-TW',
    statsSupplements: '補充品',
    statsConflicts: '衝突',
    statsStreak: '連續天數',
    statsPowered: 'AI 驅動',
    todaySchedule: '今日排程',
    noScheduleYet: '尚無排程。',
    addSuppsForSchedule: '新增補充品以查看排程',
    askAI: '詢問 Recallth AI',
    askAISubtitle: '我記得您的完整健康資料',
    askPlaceholder: '詢問補充品、劑量、交互作用…',
    quickPrompt1: '維生素D3需要與食物一起服用嗎？',
    quickPrompt2: '查看我的交互作用',
    quickPrompt3: '鎂的最佳服用時機？',
    recentConversations: '近期對話',
    noConversationsYet: '尚無對話。',
    startFirstChat: '開始第一個對話',
    conversationFallback: '對話',
    viewAllConversations: '查看所有對話 →',
    cabinetTitle: '藥箱',
    addSupplement: '新增補充品',
    searchPlaceholder: '搜尋補充品...',
    cabinetEmpty: '藥箱是空的。',
    cabinetEmptySub: '新增您的第一個補充品。',
    noResults: '找不到符合的補充品。',
    cabinetNotInCabinet: '不在藥箱中',
    isThisTheOne: '是這個嗎？',
    notThisOne: '不是這個 — 手動新增',
    aiLookupNoMatch: '找不到結果 — 請手動新增。',
    recent: '最近',
    interactionWarning: (n) => `您的藥箱中偵測到 ${n} 個交互作用`,
    addTitle: '新增補充品',
    addSubtitle: '追蹤新項目',
    addButton: '加入藥箱',
    adding: '新增中...',
    editButton: '編輯',
    saveButton: '儲存',
    saving: '儲存中...',
    cancelButton: '取消',
    deleteButton: '刪除補充品',
    deleting: '刪除中...',
    confirmDelete: '確定要刪除此補充品？',
    cannotUndo: '此操作無法復原。',
    fieldName: '名稱',
    fieldType: '類型',
    fieldDosage: '劑量',
    fieldFrequency: '頻率',
    fieldTiming: '時機',
    fieldBrand: '品牌（選填）',
    fieldNotes: '備注（選填）',
    fieldDescription: '描述',
    fieldIngredients: '成份',
    uploadPhoto: '上傳照片',
    changePhoto: '更換照片',
    uploading: '上傳中...',
    imageTooLarge: '圖片須小於 2MB',
    aiLookupButton: 'AI 自動填入產品資訊',
    aiLookupTitle: 'AI 產品搜尋',
    aiLookupHint: '輸入產品名稱（例如「PVL Whey Gold 朱古力味」），AI 會自動填入所有資料。',
    aiLookupPlaceholder: '例如 NOW Foods 鎂 400mg',
    aiLookupSearch: '搜尋',
    aiLookupSearching: '搜尋中...',
    aiLookupClear: '清除',
    aiLookupConfirmTitle: '係唔係呢隻產品？',
    aiLookupConfirm: '確認填入',
    aiLookupRetry: '重新搜尋',
    aiLookupFilled: '已由 AI 填入產品資料',
    aiLookupUndo: '復原',
    historyTitle: '歷史記錄',
    historySub: (n) => `${n} 個對話`,
    noConversationsTitle: '尚無對話',
    startConversation: '開始對話',
    noConversationsMatch: '找不到符合的對話。',
    searchConversations: '搜尋對話...',
    chatGreeting: (name) => `${name} 👋`,
    goodMorningGreet: '早安',
    newChat: '新對話',
    tapSuggestion: '點選建議或輸入問題...',
    stackReview: '堆疊審查',
    todayPlan: '今日計劃',
    chatTitle: 'Recallth AI',
    chatHeaderActive: '對話',
    chatHowCanHelp: '今日有咩可以幫到你？',
    chatSugg1: '我今日嘅補充品',
    chatSugg2: '有冇交互作用？',
    chatSugg3: '最佳服用時間',
    chatSugg4: '健身前計劃',
    chatSugg5: '助眠補充品',
    chatSugg6: '科學證據',
    chatRecent: '最近',
    chatViewAll: '查看全部',
    chatConversations: '對話記錄',
    chatSearch: '搜尋...',
    chatNoConvos: '暫無對話',
    chatNoMatches: '找不到結果',
    chatFollowUp: '繼續問...',
    chatAskAnything: '問任何關於補充品嘅問題...',
    chatExerciseContextPlaceholder: '問關於呢個健身紀錄嘅嘢...',
    chatHistory: '對話記錄',
    chatNoHistory: '暫無對話記錄。',
    chatUntitled: '未命名對話',
    chatSentImage: '已傳送圖片',
    chatImagePrompt: '呢個係咩補充品？',
    chatNoResponse: '無回應',
    chatError: '出錯了，請再試一次。',
    chatRetry: '再試',
    chatQuickActions: '快捷操作',
    chatJustNow: '剛剛',
    chatYesterday: '昨天',
    aboutMe: '關於我',
    goalsSection: '目標',
    exerciseSection: '運動',
    dietSection: '飲食',
    sleepSection: '睡眠',
    lifestyleSection: '生活方式',
    sportsSection: '運動與訓練',
    conditionsSection: '疾病與傷害',
    weakAreas: '弱項：',
    notSet: '未設定',
    updatedViaChat: '透過聊天更新',
    addedViaChat: '透過聊天新增',
    daysAgo: '天前',
    sportStatusActive: '活躍',
    sportStatusLearning: '學習中',
    sportStatusPast: '過去',
    injuryStatusActive: '活躍',
    injuryStatusRecovered: '已康復',
    profileCompletenessLabel: '您的個人資料正在建立中',
    profileCompleteTellMe: '告訴我關於您的',
    promptCheckStack: '檢查我的補充品',
    promptCheckStackDesc: '我的補充劑有交互作用嗎？',
    promptUpdateHealth: '更新我的健康狀況',
    promptUpdateHealthDesc: '我最近只睡 4-5 小時',
    promptPeriodicReview: '定期回顧',
    promptPeriodicReviewDesc: '您之前提到手腕疼痛 — 還在痛嗎？',
    whatCanIHelp: '我可以幫您什麼？',
    missingFromProfile: '您的個人資料缺少',
    tellMeAboutSleep: '告訴我關於您的睡眠',
    anyDietaryRestrictions: '有飲食限制嗎？',
    tellMeAboutExercise: '告訴我您的運動習慣',
    tellMeAboutGoals: '您的健康目標是什麼？',
    tellMeAboutLifestyle: '告訴我您的生活方式',
    tellMeAboutSports: '您做什麼運動？',
    tellMeAboutInjuries: '有任何傷病嗎？',
    savingEllipsis: '儲存中…',
    failedToSave: '儲存失敗 — 請再試一次',
    profileHistory: '歷史記錄',
    profileSchedule: '排程',
    profileDashboard: '儀表板',
    fieldAge: '年齡',
    fieldHeight: '身高',
    fieldWeight: '體重',
    fieldGender: '性別',
    fieldPrimaryGoal: '主要目標',
    fieldGoalsList: '目標（以逗號分隔）',
    fieldFitnessLevel: '健身程度',
    fieldRestrictions: '飲食限制（以逗號分隔）',
    fieldAllergies: '過敏症（以逗號分隔）',
    fieldHoursPerNight: '每晚睡眠時數',
    fieldIssues: '睡眠問題（以逗號分隔）',
    fieldStressLevel: '壓力程度',
    fieldSmokingStatus: '吸煙狀況',
    fieldAlcohol: '酒精攝取',
    language: '語言',
    logOut: '登出',
    // ── Profile security ─────────────────────────────────────────────────
    securitySection: '安全設定',
    securityPassword: '密碼',
    securityPasswordSet: '已設定密碼',
    securityGoogleLinked: '已連結 Google',
    securitySetPassword: '設定密碼',
    securitySetPasswordSub: '新增密碼，讓您可以用電子郵件登入。',
    securityNewPassword: '新密碼',
    securityPasswordHint: '至少 8 個字元',
    securityConfirmPassword: '確認密碼',
    securityRepeatPassword: '重複密碼',
    securityPasswordTooShort: '密碼至少需要 8 個字元。',
    securityPasswordMismatch: '密碼不一致。',
    securityPasswordFailed: '設定密碼失敗。',
    securityLinkGoogle: '連結 Google 帳戶',
    securityLinkGoogleSub: '在此裝置上使用 Google 更快登入。',
    securityLinking: '連結中…',
    securityGoogleNotConfigured: '未設定 Google 登入。',
    fieldActivityLevel: '活動程度',
    goalsSubtitle: '追蹤您每週的健康目標',
    goalsLogTitle: '記錄本週',
    goalsNameLabel: '目標名稱',
    goalsNamePlaceholder: '例如：更好的睡眠、更多能量',
    goalsRatingLabel: '本週表現如何？',
    goalsSubmit: '記錄本週',
    goalsSubmitting: '記錄中…',
    goalsNudgeTitle: 'AI 建議',
    goalsEmpty: '在上方記錄您的第一次每週打卡以開始追蹤',
    goalsEmptyTitle: '尚無目標記錄',
    goalsTrend: '與上週相比',
    goalsWeeks: '近 8 週',
    goalsNameRequired: '請輸入目標名稱',
    goalsRatingRequired: '請選擇評分',
    goalsSubmitError: '記錄失敗 — 請再試一次',
    // ── Goals screen redesign ────────────────────────────────────────────
    goalsPageTitle: '健康目標',
    goalsPageSubtitle: '你的健康目標會影響補充品建議',
    goalsNoGoals: '未設定目標',
    goalsNoGoalsHint: '在下方新增目標，獲取個人化補充品建議',
    goalsAddSectionHeader: '新增目標',
    goalsInputPlaceholder: '例如：我想增肌同改善睡眠...',
    goalsInterpretBtn: 'AI 分析',
    goalsInterpreting: '分析中…',
    goalsInterpretedTitle: '我理解到以下目標：',
    goalsConfirmBtn: '加入我的目標',
    goalsTryAgainBtn: '重新輸入',
    goalsSaving: '儲存中…',
    goalsRecommendationsCta: '根據你的目標獲取補充品建議 →',
    goalsDeleteError: '刪除目標失敗',
    goalsSaveError: '儲存目標失敗',
    goalsAddNote: '加備注',
    goalsNotePlaceholder: '例如：目標係6個月內加5kg肌肉...',
    goalsSaveNote: '儲存',
    goalsCancelNote: '取消',
    goalsSavingNote: '儲存中…',
    goalsSeeInsights: '查看補充品分析',
    goalsInsightsLoading: '分析你的補充品中…',
    goalsInsightsSupporting: '支持你的目標',
    goalsInsightsMissing: '建議補充',
    goalsInsightsSummary: 'AI 總結',
    goalsInsightsNoneSupporting: '你目前的補充品未直接針對此目標',
    goalsInsightsError: '無法載入分析，請再試',
    goalsAddToCabinet: '+ 補充品',
    // ── Auth ────────────────────────────────────────────────────────────
    authWelcome: '歡迎回來',
    authGetStarted: '開始使用',
    authSignInSub: '登入您的帳戶',
    authCreateSub: '建立免費帳戶',
    authSignUp: '註冊',
    authLogIn: '登入',
    authContinueGoogle: '使用 Google 繼續',
    authComingSoon: '即將推出',
    authOr: '或',
    authName: '姓名',
    authNamePlaceholder: '您的姓名',
    authEmail: '電子郵件',
    authEmailPlaceholder: 'you@example.com',
    authPassword: '密碼',
    authPasswordPlaceholder: '至少 8 個字元',
    authPasswordPlaceholderLogin: '您的密碼',
    authPleaseWait: '請稍候…',
    authCreateAccount: '建立帳戶',
    authNoAccount: '還沒有帳戶？',
    authHaveAccount: '已經有帳戶？',
    // ── Schedule ────────────────────────────────────────────────────────
    scheduleTitle: '排程',
    scheduleEmpty: '尚無排程',
    scheduleEmptySub: '新增補充品到藥箱以產生排程',
    scheduleGoToCabinet: '前往藥箱',
    slotMorning: '早上',
    slotAfternoon: '下午',
    slotEvening: '傍晚',
    slotNight: '晚上',
    slotAnytime: '任何時候',
    // ── Journal ─────────────────────────────────────────────────────────
    journalTitle: '日誌',
    journalSub: '每日記錄您的感受',
    journalLogToday: '記錄今天',
    journalMood: '心情',
    journalEnergy: '精力',
    journalNotesPlaceholder: '您今天感覺如何？',
    journalSubmit: '記錄',
    journalSave: '儲存',
    journalNoEntries: '尚無記錄',
    journalNoEntriesSub: '在上方記錄第一筆以開始',
    journalDeleteConfirm: '確定要刪除此記錄？',
    journalDelete: '刪除',
    // ── Side Effects ────────────────────────────────────────────────────
    sideEffectsTitle: '副作用',
    sideEffectsSub: '追蹤補充品對您的影響',
    sideEffectsLog: '記錄副作用',
    sideEffectsSupplement: '補充品',
    sideEffectsSelectSupp: '選擇補充品…',
    sideEffectsSuppPlaceholder: '補充品名稱',
    sideEffectsWhat: '您注意到什麼？',
    sideEffectsWhatPlaceholder: '您注意到什麼？',
    sideEffectsSeverity: '嚴重程度',
    sideEffectsMild: '輕微',
    sideEffectsModerate: '中等',
    sideEffectsSevere: '嚴重',
    sideEffectsDate: '日期',
    sideEffectsSubmit: '記錄',
    sideEffectsLogging: '記錄中…',
    sideEffectsHistory: '歷史記錄',
    sideEffectsEmpty: '尚無副作用記錄 — 追蹤補充品對您的影響',
    sideEffectsEmptyTitle: '尚無副作用',
    sideEffectsToday: '今天',
    sideEffectsDeleteConfirm: '確定要刪除？',
    sideEffectsYes: '是',
    sideEffectsNo: '否',
    // ── Progress ────────────────────────────────────────────────────────
    progressTitle: '進度',
    progressSub: '追蹤您的身體數據',
    progressLogStats: '記錄數據',
    progressWeight: '體重 (kg)',
    progressBodyFat: '體脂率 %',
    progressDate: '日期',
    progressNotes: '備注',
    progressOptional: '選填',
    progressLogging: '記錄中…',
    progressWeightPlaceholder: '例如 72.5',
    progressKgNow: '公斤',
    progressChange: '變化',
    progressEntries: '筆記錄',
    progressWeightTrend: '體重趨勢 (kg)',
    progressBfTrend: '體脂趨勢 (%)',
    progressAllEntries: '所有記錄',
    progressEmpty: '尚無數據 — 記錄您的第一筆測量',
    progressEmptySub: '使用上方表單開始。',
    progressBodyFatLabel: '% 體脂',
    progressWeightRequired: '體重為必填。',
    progressFailed: '記錄失敗 — 請再試一次。',
    // ── Bloodwork ───────────────────────────────────────────────────────
    bloodworkTitle: '血液檢查',
    bloodworkSub: '追蹤您的檢驗結果',
    bloodworkLogNew: '記錄新結果',
    bloodworkTestDate: '檢驗日期',
    bloodworkQuickAdd: '快速新增',
    bloodworkCustomMarker: '自訂指標',
    bloodworkUnit: '單位',
    bloodworkAdd: '新增',
    bloodworkValue: '數值',
    bloodworkSaving: '儲存中…',
    bloodworkLogResults: '記錄結果',
    bloodworkAnalysing: '分析中…',
    bloodworkGetAI: '取得 AI 解讀',
    bloodworkInterpretFailed: '解讀失敗 — 請再試一次',
    bloodworkEmpty: '尚無血液檢查記錄',
    bloodworkEmptySub: '在上方新增指標以追蹤檢驗結果',
    bloodworkInRange: '正常範圍',
    bloodworkBelow: '低於範圍',
    bloodworkAbove: '高於範圍',
    bloodworkMarker: '個指標',
    bloodworkMarkers: '個指標',
    // ── Doctor Prep ─────────────────────────────────────────────────────
    doctorPrepTitle: '醫師準備',
    doctorPrepSub: '下次就診時要問的問題',
    doctorPrepGenerating: '正在生成問題…',
    doctorPrepFailed: '無法生成問題',
    doctorPrepFailedSub: '請確認藥箱和個人資料有數據後再試。',
    doctorPrepRetry: '重試',
    doctorPrepReady: (n) => `${n} 個問題已準備好`,
    doctorPrepCopied: '已複製！',
    doctorPrepCopyAll: '複製全部',
    doctorPrepNoCabinet: '藥箱係空的',
    doctorPrepNoCabinetSub: '先喺藥箱加補充品，先可以生成你嘅就診問題。',
    // ── Stack Builder ───────────────────────────────────────────────────
    stackBuilderTitle: '堆疊配方',
    stackBuilderSub: '輸入健康目標，幾秒內獲得個人化補充品推薦。',
    stackBuilderPlaceholder: '例如：更好的睡眠、增肌…',
    stackBuilderGenerate: '建立配方',
    stackBuilderGenerating: '生成中…',
    stackBuilderEmpty: '建立您的個人化配方',
    stackBuilderEmptySub: '在上方輸入健康目標 — 睡眠、精力、表現、免疫 — 我們會為您推薦合適的補充品。',
    stackBuilderLoading: '正在生成您的配方…',
    stackBuilderFailed: '無法生成推薦 — 請再試一次',
    stackBuilderRetry: '重試',
    stackBuilderInStack: '已在配方中',
    stackBuilderAdded: '已新增',
    stackBuilderAddToStack: '加入配方',
    stackBuilderAdding: '新增中…',
    stackBuilderEssential: '必需',
    stackBuilderBeneficial: '有益',
    stackBuilderOptional: '可選',
    stackBuilderExGoal1: '改善睡眠',
    stackBuilderExGoal2: '增肌',
    stackBuilderExGoal3: '提升精力',
    stackBuilderSavedGoalsLabel: '你的已儲存目標',
    stackBuilderOrType: '或輸入新目標',
    // ── Notifications ───────────────────────────────────────────────────
    notificationsTitle: '通知設定',
    notificationsSub: '管理提醒、摘要和時區。',
    notificationsLoadError: '無法載入設定 — 請重新整理',
    notificationsReminders: '每日補充品提醒',
    notificationsNoReminders: '尚無提醒。在下方新增。',
    notificationsAddReminder: '新增提醒',
    notificationsDigestTitle: '每週摘要郵件',
    notificationsDigestToggle: '郵件摘要',
    notificationsDigestSub: '每週收到補充品活動摘要',
    notificationsDigestDay: '發送日',
    notificationsTimezone: '時區',
    notificationsSaved: '已儲存',
    notificationsMon: '一',
    notificationsTue: '二',
    notificationsWed: '三',
    notificationsThu: '四',
    notificationsFri: '五',
    notificationsSat: '六',
    notificationsSun: '日',
    // ── Onboarding ──────────────────────────────────────────────────────
    onboardingStep: (curr, total) => `第 ${curr} 步，共 ${total} 步`,
    onboardingGoalsTitle: '您的目標是什麼？',
    onboardingGoalsSub: '選擇所有適用的',
    onboardingGoalMuscle: '肌肉與力量',
    onboardingGoalRecovery: '恢復',
    onboardingGoalSleep: '更好的睡眠',
    onboardingGoalEnergy: '更多精力',
    onboardingGoalHealth: '整體健康',
    onboardingGoalWeight: '體重管理',
    onboardingContinue: '繼續',
    onboardingBack: '返回',
    onboardingSuppTitle: '新增第一個補充品',
    onboardingSuppSub: '之後可以在藥箱中新增更多',
    onboardingSuppName: '補充品名稱',
    onboardingSuppNamePlaceholder: '例如：肌酸、Omega-3、維生素D',
    onboardingSuppDose: '劑量',
    onboardingSuppDosePlaceholder: '例如：5g、1000mg、2顆膠囊',
    onboardingSuppTiming: '時機',
    onboardingSuppSkip: '暫時略過',
    onboardingSchedTitle: '您偏好何時服用？',
    onboardingSchedSub: '我們會根據此偏好優化您的排程',
    onboardingSchedMorning: '偏早上',
    onboardingSchedMorningSub: '中午前集中服用補充品',
    onboardingSchedEvening: '偏晚上',
    onboardingSchedEveningSub: '下午和晚上服用大部分補充品',
    onboardingFinish: '完成設定',
    // ── Evidence ────────────────────────────────────────────────────────
    evidenceStrong: '強力證據',
    evidenceGood: '良好證據',
    evidenceModerate: '中等證據',
    evidenceLimited: '有限證據',
    // ── Misc ────────────────────────────────────────────────────────────
    active: '使用中',
    conflicts: '衝突',
    interactions: '交互作用',
    failedToLoad: '載入失敗',
    suppNotFound: '找不到補充品',
    nameRequired: '名稱為必填',
    dosageRequired: '劑量為必填',
    failedToSaveChanges: '儲存失敗',
    failedToDelete: '刪除失敗',
    failedToAdd: '新增補充品失敗',
    failedToLoadHistory: '載入歷史記錄失敗',
    imageAttached: '已附加圖片',
    searchEllipsis: '搜尋或問問題…',
    msgs: '則訊息',
    messages: '則訊息',
    unknown: '未知',
    supplement: '補充品',
    // ── Relative time ───────────────────────────────────────────────────
    timeMinAgo: (n) => `${n}分鐘前`,
    timeHrAgo: (n) => `${n}小時前`,
    timeDaysAgo: (n) => `${n}天前`,
    timeYesterday: '昨天',
    // ── Nutrition Tracker ────────────────────────────────────────────────
    nutritionTitle: '營養追蹤',
    nutritionSub: '追蹤每日營養攝取',
    nutritionCategoryGym: '增肌健身',
    nutritionCategoryWeightLoss: '減重',
    nutritionCategoryDiabetes: '糖尿管理',
    nutritionCategoryKidney: '腎病管理',
    nutritionCategoryPregnancy: '孕期營養',
    nutritionCategoryCustom: '自訂',
    nutritionCalories: '卡路里',
    nutritionProtein: '蛋白質',
    nutritionCarbs: '碳水化合物',
    nutritionFat: '脂肪',
    nutritionFiber: '纖維',
    nutritionSodium: '鈉',
    nutritionSugar: '糖分',
    nutritionFolate: '葉酸',
    nutritionIron: '鐵',
    nutritionMealBreakfast: '早餐',
    nutritionMealLunch: '午餐',
    nutritionMealDinner: '晚餐',
    nutritionMealSnack: '小食',
    nutritionAiPlaceholder: '例如「午餐食了叉燒飯和凍奶茶」\n「早餐：兩顆荷包蛋、一片多士」\n「焗豬扒飯有兩塊豬扒，吃了幾口湯」',
    nutritionAiParsing: '分析中...',
    nutritionAiParsed: '找到 {n} 種食物',
    nutritionConfirm: '加入記錄',
    nutritionTotal: '合計',
    nutritionAddFood: '新增食物',
    nutritionAddTitle: '記錄食物',
    nutritionFieldFood: '食物名稱',
    nutritionFieldQuantity: '份量',
    nutritionFieldMeal: '餐別',
    nutritionEmpty: '還沒有記錄',
    nutritionEmptySub: '記錄你今天吃了什麼',
    nutritionDeleteConfirm: '確定刪除此記錄？',
    nutritionDisclaimer: '此功能非醫療建議，請諮詢醫生。',
    nutritionAlgoTitle: '如何計算目標？',
    nutritionAlgoPersonalised: '個人化 · Mifflin-St Jeor 公式',
    nutritionAlgoUpdateProfile: '更新個人資料即可重新計算。',
    nutritionAlgoDefault: '目標使用一般指引。',
    nutritionAlgoDefaultSub: '完成個人資料 — 身高、體重、年齡、性別和活動量 — 使用 Mifflin-St Jeor 公式計算適合您的目標。',
    nutritionAlgoCompleteProfile: '完善個人資料 →',
    nutritionTabAI: 'AI 分析',
    nutritionTabManual: '手動輸入',
    nutritionAiAnalyse: '分析',
    nutritionAdding: '加緊…',
    nutritionManualNamePlaceholder: '食物名稱（例如 白飯、沙拉）',
    nutritionManualQtyPlaceholder: '份量',
    nutritionManualUnitPlaceholder: '單位（例如 碗、g、杯）',
    nutritionManualAdd: '加入記錄',
    nutritionManualSaving: '儲存中…',
    nutritionChooseDrink: '選擇飲品',
    nutritionNoFoodDetails: '沒有食物詳情',
    nutritionDeleteRecord: '刪除記錄',
    nutritionDeleteEntry: '確定刪除此記錄？',
    nutritionCalHasRecord: '有記錄',
    nutritionCalToday: '今天',
    nutritionEntryDeleted: '已刪除記錄',
    nutritionUndo: '復原',
    nutritionDragHandle: '拖移',
    nutritionMoveToDate: '移到其他日期',
    nutritionMoveConfirm: '移動',
    nutritionMoveBack: '← 返回',
    nutritionCustomiseBtn: '自訂',
    nutritionCustomiseTitle: '自訂營養素',
    nutritionCustomiseSave: '儲存',
    nutritionCustomiseGoalPlaceholder: '目標',
    nutritionSelectMode: '選取',
    nutritionSelectCancel: '取消',
    nutritionSelectAll: '全選',
    nutritionBatchDelete: '刪除（{n}）',
    nutritionBatchConfirmTitle: '刪除 {n} 個項目？',
    nutritionBatchConfirmSub: '此操作無法復原。',
    nutritionBatchDeleting: '刪除中…',
    foodDbTitle: '食物資料庫',
    foodDbSearchPlaceholder: '搜尋食物名稱（中文或英文）…',
    foodDbCommonFoods: '常見港式食物',
    foodDbResultsCount: '{n} 個結果',
    foodDbEmpty: '找不到食物',
    foodDbEmptySub: '請嘗試其他搜尋詞',
    foodDbCategoryAll: '全部',
    foodDbCategoryRiceNoodles: '飯麵類',
    foodDbCategoryProtein: '蛋白質',
    foodDbCategoryDimSum: '點心',
    foodDbCategorySoup: '湯類',
    foodDbCategoryBreadPastry: '麵包糕點',
    foodDbCategoryDrinks: '飲品',
    foodDbCategoryDesserts: '甜品',
    foodDbCategorySnacks: '小食',
    foodDbCategoryFastFood: '快餐',
    foodDbCategoryWholeFood: '天然食品',
    foodDbCategoryPackaged: '包裝食品',
    foodDbFlagHighProtein: '高蛋白',
    foodDbFlagHighFiber: '高纖維',
    foodDbFlagLowSugar: '低糖',
    foodDbFlagLowSodium: '低鈉',
    foodDbFlagLowCalorie: '低卡',
    foodDbFlagHighCalorie: '高卡',
    foodDbPerServing: '每份',
    foodDbServings: '份數',
    foodDbAdd: '加入記錄',
    back: '返回',
    freqDaily: '每日',
    freqTwiceDaily: '每日兩次',
    freqAsNeeded: '按需要',
    timingMorning: '早上',
    timingPreWorkout: '健身前',
    timingWithMeals: '隨餐',
    timingEvening: '傍晚',
    timingBeforeBed: '睡前',
    nutritionSaved: '已儲存',
    nutritionUploadLabelPhoto: '上傳營養標籤相片',
    nutritionTapToSelectPhoto: '點擊選取相片',
    nutritionReadingLabel: '讀取營養標籤中...',
    nutritionTryAgain: '再試一次',
    nutritionExtractedFromPhoto: '從相片提取',
    nutritionUseThis: '使用此項',
    nutritionRetake: '重拍',
    nutritionGoToToday: '今天',
    nutritionViewMonth: '查看月份',
    nutritionCollapse: '收起',
    nutritionGoalMode: '目標模式',
    nutritionDidYouMean: '是否指的是？',
    nutritionRecTitle: '補充劑建議',
    nutritionRecAllGood: '您今天的補充劑已涵蓋所有營養缺口。',
  },

  'zh-HK': {
    home: '主頁',
    chat: '對話',
    cabinet: '藥箱',
    profile: '個人',
    history: '歷史記錄',
    schedule: '時間表',
    stackBuilder: '配方搭配',
    doctorPrep: '醫生準備',
    sideEffects: '副作用',
    journal: '日誌',
    progress: '進度',
    goals: '目標',
    notifications: '通知設定',
    nutrition: '營養追蹤',
    foodDb: '食物資料庫',
    exercise: '運動',
    logActivity: '記錄運動',
    noWorkoutsYet: '未有運動紀錄',
    logFirstActivity: '記錄你的第一次運動',
    activityType: '運動類型',
    intensityEasy: '輕鬆',
    intensityModerate: '中等',
    intensityHard: '高強度',
    addExercise: '+ 加動作',
    saveSession: '儲存',
    exerciseAiPlaceholder: '描述你嘅運動…例如「bench press 3組10下80kg，gym 60分鐘」或「跑咗5公里，45分鐘」',
    parseWithAI: 'AI 解析',
    parsing: '解析中...',
    parsedPreview: '解析結果',
    editManually: '手動修改',
    fillManually: '手動填寫',
    thisWeek: '本週',
    lastWeek: '上週',
    activityGym: '健身室',
    activityRunning: '跑步',
    activitySwimming: '游泳',
    activityBasketball: '籃球',
    activityBadminton: '羽毛球',
    activityCycling: '單車',
    activityYoga: '瑜伽',
    activityHiking: '行山',
    activityOther: '其他',
    date: '日期',
    startTraining: '開始訓練',
    noPlanExercises: '此計劃未包含具體動作，可手動加入',
    exTypeStrength: '重訓',
    exTypeBodyweight: '自重',
    exTypeTimed: '計時',
    exTypeCardio: '有氧',
    exTypeSession: '整體',
    filterAll: '全部',
    weekSessions: '次運動',
    weekMinutes: '分鐘（本週）',
    noSessionsForFilter: '呢個運動類型未有紀錄。',
    logFirstActivityHint: '開始記錄，追蹤你嘅進度。',
    duration: '時間',
    distance: '距離',
    exercises: '動作',
    notes: '備註',
    editSession: '編輯紀錄',
    save: '儲存',
    saving: '儲存緊...',
    deleteSession: '刪除紀錄',
    deleteSessionConfirm: '呢個運動紀錄將會被永久刪除。',
    deleteConfirmBtn: '刪除',
    deleting: '刪除中...',
    cancel: '取消',
    back: '返回',
    freePlan: '免費計劃',
    menu: '選單',
    signOut: '登出',
    goodMorning: '早晨',
    goodAfternoon: '午安',
    goodEvening: '晚安',
    locale: 'zh-HK',
    statsSupplements: '補充品',
    statsConflicts: '衝突',
    statsStreak: '連續打卡',
    statsPowered: 'AI 支援',
    todaySchedule: '今日時間表',
    noScheduleYet: '未有時間表。',
    addSuppsForSchedule: '加補充品先睇到時間表',
    askAI: '問 Recallth AI',
    askAISubtitle: '我記住曬你嘅健康資料',
    askPlaceholder: '問補充品、劑量、交互作用…',
    quickPrompt1: '食D3要唔要同食物一齊食？',
    quickPrompt2: '查我嘅交互作用',
    quickPrompt3: '鎂最好幾時食？',
    recentConversations: '最近對話',
    noConversationsYet: '未有對話。',
    startFirstChat: '開始第一個對話',
    conversationFallback: '對話',
    viewAllConversations: '睇所有對話 →',
    cabinetTitle: '藥箱',
    addSupplement: '加補充品',
    searchPlaceholder: '搵補充品...',
    cabinetEmpty: '藥箱係空㗎。',
    cabinetEmptySub: '加你第一個補充品。',
    noResults: '搵唔到符合嘅補充品。',
    cabinetNotInCabinet: '唔係喺藥箱入面',
    isThisTheOne: '係唔係呢個？',
    notThisOne: '唔係呢個 — 手動加',
    aiLookupNoMatch: '搵唔到結果 — 請手動加。',
    recent: '最近',
    interactionWarning: (n) => `你嘅藥箱有 ${n} 個交互作用`,
    addTitle: '加補充品',
    addSubtitle: '追蹤新項目',
    addButton: '加入藥箱',
    adding: '加緊...',
    editButton: '編輯',
    saveButton: '儲存',
    saving: '儲存緊...',
    cancelButton: '取消',
    deleteButton: '刪除補充品',
    deleting: '刪緊...',
    confirmDelete: '確定要刪除呢個補充品？',
    cannotUndo: '呢個操作係冇得返轉頭㗎。',
    fieldName: '名稱',
    fieldType: '類型',
    fieldDosage: '劑量',
    fieldFrequency: '頻率',
    fieldTiming: '時機',
    fieldBrand: '品牌（可選）',
    fieldNotes: '備注（可選）',
    fieldDescription: '描述',
    fieldIngredients: '成份',
    uploadPhoto: '上傳相片',
    changePhoto: '換相片',
    uploading: '上傳緊...',
    imageTooLarge: '相片要細過 2MB',
    aiLookupButton: 'AI 自動填寫產品資料',
    aiLookupTitle: 'AI 產品搜尋',
    aiLookupHint: '打個產品名（例如「PVL Whey Gold 朱古力味」），AI 會幫你填晒所有資料。',
    aiLookupPlaceholder: '例如 NOW Foods 鎂 400mg',
    aiLookupSearch: '搜尋',
    aiLookupSearching: '搵緊...',
    aiLookupClear: '清除',
    aiLookupConfirmTitle: '係咪呢隻產品？',
    aiLookupConfirm: '確認填入',
    aiLookupRetry: '再搵過',
    aiLookupFilled: 'AI 已幫你填咗產品資料',
    aiLookupUndo: '復原',
    historyTitle: '歷史記錄',
    historySub: (n) => `${n} 個對話`,
    noConversationsTitle: '未有對話',
    startConversation: '開始對話',
    noConversationsMatch: '搵唔到符合嘅對話。',
    searchConversations: '搵對話...',
    chatGreeting: (name) => `${name} 👋`,
    goodMorningGreet: '早晨',
    newChat: '新對話',
    tapSuggestion: '撳建議或者問任何野...',
    stackReview: '堆疊審查',
    todayPlan: '今日計劃',
    chatTitle: 'Recallth AI',
    chatHeaderActive: '對話',
    chatHowCanHelp: '今日有咩可以幫到你？',
    chatSugg1: '我今日嘅補充品',
    chatSugg2: '有冇交互作用？',
    chatSugg3: '最佳服用時間',
    chatSugg4: '健身前計劃',
    chatSugg5: '助眠補充品',
    chatSugg6: '科學證據',
    chatRecent: '最近',
    chatViewAll: '睇晒全部',
    chatConversations: '對話記錄',
    chatSearch: '搜尋...',
    chatNoConvos: '暫時冇對話',
    chatNoMatches: '搵唔到',
    chatFollowUp: '繼續問...',
    chatAskAnything: '問任何關於補充品嘅問題...',
    chatExerciseContextPlaceholder: '問關於呢個健身紀錄嘅嘢...',
    chatHistory: '對話記錄',
    chatNoHistory: '暫時冇對話記錄。',
    chatUntitled: '未命名對話',
    chatSentImage: '已傳送圖片',
    chatImagePrompt: '呢個係咩補充品？',
    chatNoResponse: '冇回應',
    chatError: '出咗錯，請再試過。',
    chatRetry: '再試過',
    chatQuickActions: '快捷操作',
    chatJustNow: '啱啱',
    chatYesterday: '尋日',
    aboutMe: '關於我',
    goalsSection: '目標',
    exerciseSection: '運動',
    dietSection: '飲食',
    sleepSection: '睡眠',
    lifestyleSection: '生活方式',
    sportsSection: '運動同訓練',
    conditionsSection: '傷病同狀況',
    weakAreas: '弱項：',
    notSet: '未設定',
    updatedViaChat: '透過對話更新',
    addedViaChat: '透過對話新增',
    daysAgo: '日前',
    sportStatusActive: '活躍',
    sportStatusLearning: '學緊',
    sportStatusPast: '以前',
    injuryStatusActive: '仲係',
    injuryStatusRecovered: '好返',
    profileCompletenessLabel: '你嘅個人資料建緊',
    profileCompleteTellMe: '話我知你嘅',
    promptCheckStack: '查我嘅補充品',
    promptCheckStackDesc: '我啲補充劑有冇交互作用？',
    promptUpdateHealth: '更新我嘅健康',
    promptUpdateHealthDesc: '我最近淨係瞓 4-5 個鐘',
    promptPeriodicReview: '定期回顧',
    promptPeriodicReviewDesc: '你之前講過手腕痛 — 仲痛唔痛？',
    whatCanIHelp: '有乜可以幫到你？',
    missingFromProfile: '你嘅個人資料缺少',
    tellMeAboutSleep: '講下你嘅睡眠',
    anyDietaryRestrictions: '有冇飲食限制？',
    tellMeAboutExercise: '講下你嘅運動習慣',
    tellMeAboutGoals: '你嘅健康目標係乜？',
    tellMeAboutLifestyle: '講下你嘅生活方式',
    tellMeAboutSports: '你做咩運動？',
    tellMeAboutInjuries: '有冇受傷或者身體問題？',
    savingEllipsis: '儲存緊…',
    failedToSave: '儲存失敗 — 再試一次',
    profileHistory: '歷史記錄',
    profileSchedule: '時間表',
    profileDashboard: '主頁',
    fieldAge: '年齡',
    fieldHeight: '身高',
    fieldWeight: '體重',
    fieldGender: '性別',
    fieldPrimaryGoal: '主要目標',
    fieldGoalsList: '目標（以逗號分隔）',
    fieldFitnessLevel: '健身水平',
    fieldRestrictions: '飲食限制（以逗號分隔）',
    fieldAllergies: '敏感症（以逗號分隔）',
    fieldHoursPerNight: '每晚睡眠時數',
    fieldIssues: '睡眠問題（以逗號分隔）',
    fieldStressLevel: '壓力程度',
    fieldSmokingStatus: '吸煙狀況',
    fieldAlcohol: '飲酒情況',
    language: '語言',
    logOut: '登出',
    // ── Profile security ─────────────────────────────────────────────────
    securitySection: '安全設定',
    securityPassword: '密碼',
    securityPasswordSet: '已設定密碼',
    securityGoogleLinked: '已連結 Google',
    securitySetPassword: '設定密碼',
    securitySetPasswordSub: '加密碼咁你就可以用電郵登入。',
    securityNewPassword: '新密碼',
    securityPasswordHint: '至少 8 個字',
    securityConfirmPassword: '確認密碼',
    securityRepeatPassword: '重複密碼',
    securityPasswordTooShort: '密碼至少要 8 個字。',
    securityPasswordMismatch: '兩次密碼唔同。',
    securityPasswordFailed: '設定密碼失敗。',
    securityLinkGoogle: '連結 Google 帳戶',
    securityLinkGoogleSub: '喺呢個裝置用 Google 登入更快。',
    securityLinking: '連結緊…',
    securityGoogleNotConfigured: '未設定 Google 登入。',
    fieldActivityLevel: '活動程度',
    goalsSubtitle: '追蹤你每週嘅健康目標',
    goalsLogTitle: '記錄本週',
    goalsNameLabel: '目標名稱',
    goalsNamePlaceholder: '例如：瞓好啲、精力多啲',
    goalsRatingLabel: '今週表現點？',
    goalsSubmit: '記錄本週',
    goalsSubmitting: '記錄緊…',
    goalsNudgeTitle: 'AI 建議',
    goalsEmpty: '喺上面記錄你第一次每週打卡，開始追蹤',
    goalsEmptyTitle: '未有目標記錄',
    goalsTrend: '對比上週',
    goalsWeeks: '近 8 週',
    goalsNameRequired: '請輸入目標名稱',
    goalsRatingRequired: '請揀評分',
    goalsSubmitError: '記錄失敗 — 請再試一次',
    // ── Goals screen redesign ────────────────────────────────────────────
    goalsPageTitle: '健康目標',
    goalsPageSubtitle: '你的健康目標會影響補充品建議',
    goalsNoGoals: '未設定目標',
    goalsNoGoalsHint: '在下方新增目標，獲取個人化補充品建議',
    goalsAddSectionHeader: '新增目標',
    goalsInputPlaceholder: '例如：我想增肌同改善睡眠...',
    goalsInterpretBtn: 'AI 分析',
    goalsInterpreting: '分析中…',
    goalsInterpretedTitle: '我理解到以下目標：',
    goalsConfirmBtn: '加入我的目標',
    goalsTryAgainBtn: '重新輸入',
    goalsSaving: '儲存中…',
    goalsRecommendationsCta: '根據你的目標獲取補充品建議 →',
    goalsDeleteError: '刪除目標失敗',
    goalsSaveError: '儲存目標失敗',
    goalsAddNote: '加備注',
    goalsNotePlaceholder: '例如：目標係6個月內加5kg肌肉...',
    goalsSaveNote: '儲存',
    goalsCancelNote: '取消',
    goalsSavingNote: '儲存中…',
    goalsSeeInsights: '查看補充品分析',
    goalsInsightsLoading: '分析你的補充品中…',
    goalsInsightsSupporting: '支持你的目標',
    goalsInsightsMissing: '建議補充',
    goalsInsightsSummary: 'AI 總結',
    goalsInsightsNoneSupporting: '你目前的補充品未直接針對此目標',
    goalsInsightsError: '無法載入分析，請再試',
    goalsAddToCabinet: '+ 補充品',
    // ── Auth ────────────────────────────────────────────────────────────
    authWelcome: '歡迎返嚟',
    authGetStarted: '開始用',
    authSignInSub: '登入你嘅帳戶',
    authCreateSub: '建立免費帳戶',
    authSignUp: '註冊',
    authLogIn: '登入',
    authContinueGoogle: '用 Google 繼續',
    authComingSoon: '即將推出',
    authOr: '或',
    authName: '名',
    authNamePlaceholder: '你嘅名',
    authEmail: '電郵',
    authEmailPlaceholder: 'you@example.com',
    authPassword: '密碼',
    authPasswordPlaceholder: '至少 8 個字',
    authPasswordPlaceholderLogin: '你嘅密碼',
    authPleaseWait: '等等…',
    authCreateAccount: '建立帳戶',
    authNoAccount: '未有帳戶？',
    authHaveAccount: '已經有帳戶？',
    // ── Schedule ────────────────────────────────────────────────────────
    scheduleTitle: '時間表',
    scheduleEmpty: '未有時間表',
    scheduleEmptySub: '加補充品入藥箱先有時間表',
    scheduleGoToCabinet: '去藥箱',
    slotMorning: '朝早',
    slotAfternoon: '下晝',
    slotEvening: '傍晚',
    slotNight: '夜晚',
    slotAnytime: '任何時候',
    // ── Journal ─────────────────────────────────────────────────────────
    journalTitle: '日誌',
    journalSub: '每日記錄你嘅感受',
    journalLogToday: '記錄今日',
    journalMood: '心情',
    journalEnergy: '精力',
    journalNotesPlaceholder: '你今日感覺點？',
    journalSubmit: '記錄',
    journalSave: '儲存',
    journalNoEntries: '未有記錄',
    journalNoEntriesSub: '喺上面記錄第一筆開始',
    journalDeleteConfirm: '確定要刪除呢筆記錄？',
    journalDelete: '刪除',
    // ── Side Effects ────────────────────────────────────────────────────
    sideEffectsTitle: '副作用',
    sideEffectsSub: '追蹤補充品對你嘅影響',
    sideEffectsLog: '記錄副作用',
    sideEffectsSupplement: '補充品',
    sideEffectsSelectSupp: '揀補充品…',
    sideEffectsSuppPlaceholder: '補充品名',
    sideEffectsWhat: '你留意到啲咩？',
    sideEffectsWhatPlaceholder: '你留意到啲咩？',
    sideEffectsSeverity: '嚴重程度',
    sideEffectsMild: '輕微',
    sideEffectsModerate: '中等',
    sideEffectsSevere: '嚴重',
    sideEffectsDate: '日期',
    sideEffectsSubmit: '記錄',
    sideEffectsLogging: '記錄緊…',
    sideEffectsHistory: '歷史記錄',
    sideEffectsEmpty: '未有副作用記錄 — 追蹤補充品對你嘅影響',
    sideEffectsEmptyTitle: '未有副作用',
    sideEffectsToday: '今日',
    sideEffectsDeleteConfirm: '確定要刪？',
    sideEffectsYes: '係',
    sideEffectsNo: '唔係',
    // ── Progress ────────────────────────────────────────────────────────
    progressTitle: '進度',
    progressSub: '追蹤你嘅身體數據',
    progressLogStats: '記錄數據',
    progressWeight: '體重 (kg)',
    progressBodyFat: '體脂率 %',
    progressDate: '日期',
    progressNotes: '備注',
    progressOptional: '可選',
    progressLogging: '記錄緊…',
    progressWeightPlaceholder: '例如 72.5',
    progressKgNow: '公斤',
    progressChange: '變化',
    progressEntries: '筆記錄',
    progressWeightTrend: '體重趨勢 (kg)',
    progressBfTrend: '體脂趨勢 (%)',
    progressAllEntries: '所有記錄',
    progressEmpty: '未有數據 — 記錄你第一筆量度',
    progressEmptySub: '用上面嘅表格開始。',
    progressBodyFatLabel: '% 體脂',
    progressWeightRequired: '體重必填。',
    progressFailed: '記錄失敗 — 再試一次。',
    // ── Bloodwork ───────────────────────────────────────────────────────
    bloodworkTitle: '驗血報告',
    bloodworkSub: '追蹤你嘅檢驗結果',
    bloodworkLogNew: '記錄新結果',
    bloodworkTestDate: '檢驗日期',
    bloodworkQuickAdd: '快速加',
    bloodworkCustomMarker: '自訂指標',
    bloodworkUnit: '單位',
    bloodworkAdd: '加',
    bloodworkValue: '數值',
    bloodworkSaving: '儲存緊…',
    bloodworkLogResults: '記錄結果',
    bloodworkAnalysing: '分析緊…',
    bloodworkGetAI: '攞 AI 解讀',
    bloodworkInterpretFailed: '解讀失敗 — 再試一次',
    bloodworkEmpty: '未有驗血記錄',
    bloodworkEmptySub: '喺上面加指標嚟追蹤檢驗結果',
    bloodworkInRange: '正常範圍',
    bloodworkBelow: '低過範圍',
    bloodworkAbove: '高過範圍',
    bloodworkMarker: '個指標',
    bloodworkMarkers: '個指標',
    // ── Doctor Prep ─────────────────────────────────────────────────────
    doctorPrepTitle: '醫生準備',
    doctorPrepSub: '下次睇醫生時要問嘅問題',
    doctorPrepGenerating: '生成緊問題…',
    doctorPrepFailed: '生成唔到問題',
    doctorPrepFailedSub: '確認藥箱同個人資料有數據先再試。',
    doctorPrepRetry: '重試',
    doctorPrepReady: (n) => `${n} 條問題準備好`,
    doctorPrepCopied: '已複製！',
    doctorPrepCopyAll: '複製全部',
    doctorPrepNoCabinet: '藥箱係空㗎',
    doctorPrepNoCabinetSub: '先喺藥箱加補充品先，咁先可以幫你生成睇醫生嘅問題。',
    // ── Stack Builder ───────────────────────────────────────────────────
    stackBuilderTitle: '配方搭配',
    stackBuilderSub: '輸入健康目標，幾秒內攞到個人化補充品推薦。',
    stackBuilderPlaceholder: '例如：瞓好啲、增肌…',
    stackBuilderGenerate: '建立配方',
    stackBuilderGenerating: '生成緊…',
    stackBuilderEmpty: '建立你嘅個人化配方',
    stackBuilderEmptySub: '喺上面輸入健康目標 — 瞓覺、精力、表現、免疫 — 我哋會推薦啱你嘅補充品。',
    stackBuilderLoading: '生成緊你嘅配方…',
    stackBuilderFailed: '生成唔到推薦 — 再試一次',
    stackBuilderRetry: '重試',
    stackBuilderInStack: '已經喺配方入面',
    stackBuilderAdded: '已加',
    stackBuilderAddToStack: '加入配方',
    stackBuilderAdding: '加緊…',
    stackBuilderEssential: '必需',
    stackBuilderBeneficial: '有益',
    stackBuilderOptional: '可選',
    stackBuilderExGoal1: '瞓好啲',
    stackBuilderExGoal2: '增肌',
    stackBuilderExGoal3: '精力多啲',
    stackBuilderSavedGoalsLabel: '你嘅已儲存目標',
    stackBuilderOrType: '或者輸入新目標',
    // ── Notifications ───────────────────────────────────────────────────
    notificationsTitle: '通知設定',
    notificationsSub: '管理提醒、摘要同時區。',
    notificationsLoadError: '載入唔到設定 — 重新整理試下',
    notificationsReminders: '每日補充品提醒',
    notificationsNoReminders: '未有提醒。喺下面加。',
    notificationsAddReminder: '加提醒',
    notificationsDigestTitle: '每週摘要電郵',
    notificationsDigestToggle: '電郵摘要',
    notificationsDigestSub: '每週收到補充品活動摘要',
    notificationsDigestDay: '幾時寄',
    notificationsTimezone: '時區',
    notificationsSaved: '已儲存',
    notificationsMon: '一',
    notificationsTue: '二',
    notificationsWed: '三',
    notificationsThu: '四',
    notificationsFri: '五',
    notificationsSat: '六',
    notificationsSun: '日',
    // ── Onboarding ──────────────────────────────────────────────────────
    onboardingStep: (curr, total) => `第 ${curr} 步，共 ${total} 步`,
    onboardingGoalsTitle: '你嘅目標係咩？',
    onboardingGoalsSub: '揀晒所有啱嘅',
    onboardingGoalMuscle: '肌肉同力量',
    onboardingGoalRecovery: '恢復',
    onboardingGoalSleep: '瞓好啲',
    onboardingGoalEnergy: '精力多啲',
    onboardingGoalHealth: '整體健康',
    onboardingGoalWeight: '體重管理',
    onboardingContinue: '繼續',
    onboardingBack: '返回',
    onboardingSuppTitle: '加你第一個補充品',
    onboardingSuppSub: '之後可以喺藥箱加多啲',
    onboardingSuppName: '補充品名',
    onboardingSuppNamePlaceholder: '例如：肌酸、Omega-3、維他命D',
    onboardingSuppDose: '劑量',
    onboardingSuppDosePlaceholder: '例如：5g、1000mg、2粒膠囊',
    onboardingSuppTiming: '時機',
    onboardingSuppSkip: '暫時略過',
    onboardingSchedTitle: '你鐘意幾時食？',
    onboardingSchedSub: '我哋會根據呢個偏好優化你嘅時間表',
    onboardingSchedMorning: '偏朝早',
    onboardingSchedMorningSub: '中午前集中食補充品',
    onboardingSchedEvening: '偏夜晚',
    onboardingSchedEveningSub: '下晝同夜晚食大部分補充品',
    onboardingFinish: '完成設定',
    // ── Evidence ────────────────────────────────────────────────────────
    evidenceStrong: '強力證據',
    evidenceGood: '良好證據',
    evidenceModerate: '中等證據',
    evidenceLimited: '有限證據',
    // ── Misc ────────────────────────────────────────────────────────────
    active: '使用中',
    conflicts: '衝突',
    interactions: '交互作用',
    failedToLoad: '載入失敗',
    suppNotFound: '搵唔到補充品',
    nameRequired: '名稱必填',
    dosageRequired: '劑量必填',
    failedToSaveChanges: '儲存失敗',
    failedToDelete: '刪除失敗',
    failedToAdd: '加補充品失敗',
    failedToLoadHistory: '載入歷史記錄失敗',
    imageAttached: '已附圖片',
    searchEllipsis: '搜尋或問問題…',
    msgs: '則訊息',
    messages: '則訊息',
    unknown: '未知',
    supplement: '補充品',
    // ── Relative time ───────────────────────────────────────────────────
    timeMinAgo: (n) => `${n}分鐘前`,
    timeHrAgo: (n) => `${n}個鐘前`,
    timeDaysAgo: (n) => `${n}日前`,
    timeYesterday: '尋日',
    // ── Nutrition Tracker ────────────────────────────────────────────────
    nutritionTitle: '營養追蹤',
    nutritionSub: '追蹤每日營養攝取',
    nutritionCategoryGym: '增肌健身',
    nutritionCategoryWeightLoss: '減重',
    nutritionCategoryDiabetes: '糖尿管理',
    nutritionCategoryKidney: '腎病管理',
    nutritionCategoryPregnancy: '孕期營養',
    nutritionCategoryCustom: '自訂',
    nutritionCalories: '卡路里',
    nutritionProtein: '蛋白質',
    nutritionCarbs: '碳水',
    nutritionFat: '脂肪',
    nutritionFiber: '纖維',
    nutritionSodium: '鈉',
    nutritionSugar: '糖分',
    nutritionFolate: '葉酸',
    nutritionIron: '鐵',
    nutritionMealBreakfast: '早餐',
    nutritionMealLunch: '午餐',
    nutritionMealDinner: '晚餐',
    nutritionMealSnack: '小食',
    nutritionAiPlaceholder: '例如「lunch食咗叉燒飯同凍檸茶」\n「早餐：兩隻煎蛋、一塊多士」\n「焗豬扒飯有兩塊豬扒，食咗幾啖湯」',
    nutritionAiParsing: '分析緊...',
    nutritionAiParsed: '搵到 {n} 種食物',
    nutritionConfirm: '加入記錄',
    nutritionTotal: '合計',
    nutritionAddFood: '新增食物',
    nutritionAddTitle: '記錄食物',
    nutritionFieldFood: '食物名稱',
    nutritionFieldQuantity: '份量',
    nutritionFieldMeal: '餐別',
    nutritionEmpty: '未有記錄',
    nutritionEmptySub: '記錄你今日食咗咩',
    nutritionDeleteConfirm: '確定刪除呢條記錄？',
    nutritionDisclaimer: '呢個唔係醫療建議，請諮詢醫生。',
    nutritionAlgoTitle: '點計營養目標？',
    nutritionAlgoPersonalised: '個人化 · Mifflin-St Jeor 公式',
    nutritionAlgoUpdateProfile: '更新個人資料即可重新計算。',
    nutritionAlgoDefault: '目標係用緊一般指引。',
    nutritionAlgoDefaultSub: '完成你嘅個人資料 — 身高、體重、年齡、性別同活動量 — 用 Mifflin-St Jeor 公式計算適合你身體嘅目標。',
    nutritionAlgoCompleteProfile: '完善個人資料 →',
    nutritionTabAI: 'AI 分析',
    nutritionTabManual: '手動輸入',
    nutritionAiAnalyse: '分析',
    nutritionAdding: '加緊…',
    nutritionManualNamePlaceholder: '食物名稱（例如 白飯、沙律）',
    nutritionManualQtyPlaceholder: '份量',
    nutritionManualUnitPlaceholder: '單位（例如 碗、g、杯）',
    nutritionManualAdd: '加入記錄',
    nutritionManualSaving: '儲存緊…',
    nutritionChooseDrink: '揀飲品',
    nutritionNoFoodDetails: '未有食物詳情',
    nutritionDeleteRecord: '刪除記錄',
    nutritionDeleteEntry: '確定刪除呢條記錄？',
    nutritionCalHasRecord: '有記錄',
    nutritionCalToday: '今日',
    nutritionEntryDeleted: '已刪除記錄',
    nutritionUndo: '復原',
    nutritionDragHandle: '拖移',
    nutritionMoveToDate: '移到其他日期',
    nutritionMoveConfirm: '移動',
    nutritionMoveBack: '← 返回',
    nutritionCustomiseBtn: '自訂',
    nutritionCustomiseTitle: '自訂營養素',
    nutritionCustomiseSave: '儲存',
    nutritionCustomiseGoalPlaceholder: '目標',
    nutritionSelectMode: '選取',
    nutritionSelectCancel: '取消',
    nutritionSelectAll: '全選',
    nutritionBatchDelete: '刪除（{n}）',
    nutritionBatchConfirmTitle: '刪除 {n} 個項目？',
    nutritionBatchConfirmSub: '此操作無法復原。',
    nutritionBatchDeleting: '刪除緊…',
    foodDbTitle: '食物資料庫',
    foodDbSearchPlaceholder: '搜尋食物名稱（中英文）…',
    foodDbCommonFoods: '常見港式食物',
    foodDbResultsCount: '{n} 個結果',
    foodDbEmpty: '搵唔到食物',
    foodDbEmptySub: '試下其他搜尋詞',
    foodDbCategoryAll: '全部',
    foodDbCategoryRiceNoodles: '飯麵類',
    foodDbCategoryProtein: '蛋白質',
    foodDbCategoryDimSum: '點心',
    foodDbCategorySoup: '湯類',
    foodDbCategoryBreadPastry: '麵包糕點',
    foodDbCategoryDrinks: '飲品',
    foodDbCategoryDesserts: '甜品',
    foodDbCategorySnacks: '小食',
    foodDbCategoryFastFood: '快餐',
    foodDbCategoryWholeFood: '天然食物',
    foodDbCategoryPackaged: '包裝食品',
    foodDbFlagHighProtein: '高蛋白',
    foodDbFlagHighFiber: '高纖維',
    foodDbFlagLowSugar: '低糖',
    foodDbFlagLowSodium: '低鈉',
    foodDbFlagLowCalorie: '低卡',
    foodDbFlagHighCalorie: '高卡',
    foodDbPerServing: '每份',
    foodDbServings: '份數',
    foodDbAdd: '加入記錄',
    back: '返回',
    freqDaily: '每日',
    freqTwiceDaily: '每日兩次',
    freqAsNeeded: '按需要',
    timingMorning: '朝早',
    timingPreWorkout: '健身前',
    timingWithMeals: '隨餐',
    timingEvening: '傍晚',
    timingBeforeBed: '瞓前',
    nutritionSaved: '已儲存',
    nutritionUploadLabelPhoto: '上傳營養標籤相片',
    nutritionTapToSelectPhoto: '撳呢度揀相片',
    nutritionReadingLabel: '讀取營養標籤中...',
    nutritionTryAgain: '再試一次',
    nutritionExtractedFromPhoto: '從相片提取',
    nutritionUseThis: '用呢個',
    nutritionRetake: '重拍',
    nutritionGoToToday: '今日',
    nutritionViewMonth: '睇月份',
    nutritionCollapse: '收起',
    nutritionGoalMode: '目標模式',
    nutritionDidYouMean: '你係咪指？',
    nutritionRecTitle: '補充劑建議',
    nutritionRecAllGood: '你今日嘅補充劑已涵蓋所有營養缺口。',
  },
}

const LanguageContext = createContext()

// ── AI analyser placeholder pool ──────────────────────────────────────────────
const AI_PLACEHOLDER_POOL = {
  en: [
    'Had a chicken sandwich and a latte for lunch',
    'Breakfast: 2 scrambled eggs, toast, and orange juice',
    'Just a few bites of fried rice, maybe half a bowl',
    'Dinner was a bowl of ramen with chashu and soft egg',
    'McDonald\'s double cheeseburger, medium fries, Coke',
    'About 3 pieces of sushi and a miso soup',
    'Snack: a banana and a handful of almonds',
    'Chicken rice from the hawker stall, drumstick portion',
    'Homemade pasta with tomato sauce, one serving',
    'Two slices of pepperoni pizza for dinner',
    'Green smoothie — spinach, banana, almond milk, protein powder',
    'Afternoon snack: Greek yogurt with granola and blueberries',
    'Grilled salmon fillet with steamed broccoli and rice',
    'Just a coffee with oat milk — no food',
    'Char siu bao (3 pieces) and a cup of jasmine tea',
    'Instant noodles with an egg and some greens',
    'Korean bibimbap with mixed veggies, beef, and a fried egg',
    'Half an avocado on sourdough toast with a poached egg',
    'Bubble tea — taro milk tea, 50% sugar, full ice, large',
    'Takeaway fish and chips, ate most of it',
    'Protein bar after the gym — Quest Cookies & Cream',
    'Congee with century egg and lean pork, about 2 bowls',
    'Steak dinner — 200g sirloin, mashed potato, side salad',
    'Fruit plate: watermelon, mango, dragon fruit',
    'Late night snack: crackers and hummus',
  ],
  'zh-HK': [
    '午餐食咗叉燒飯同埋一杯凍奶茶',
    '早餐：兩隻煎蛋、一片多士、一杯橙汁',
    '食咗少少炒飯，大概半碗咁上下',
    '晚餐係一碗叉燒拉麵，有溏心蛋',
    '麥當勞雙層芝士漢堡、中薯條、可樂',
    '食咗大概三件壽司同一碗味噌湯',
    '小食：一隻香蕉同一小把杏仁',
    '雞髀飯，街邊大排檔嗰種，一份',
    '自煮意粉加茄汁，一人份量',
    '晚飯食咗兩片薄餅，有香腸係上面',
    '青瓜薄荷奶昔——菠菜、香蕉、杏仁奶、蛋白粉',
    '下午茶：希臘乳酪加格蘭諾拉麥片同藍莓',
    '燒三文魚配蒸西蘭花同白飯',
    '只係飲咗一杯燕麥拿鐵，冇食嘢',
    '飲咗三杯叉燒包同一杯香片茶',
    '公仔麵加咗隻蛋同少少菜',
    '韓式石鍋拌飯，有牛肉同各種蔬菜',
    '牛油果多士加一隻水波蛋，全麥包',
    '珍珠奶茶——芋頭味，五分甜，正常冰，大杯',
    '外賣炸魚薯條，食咗大部分',
    '健身後食咗一條蛋白棒',
    '皮蛋瘦肉粥，食咗兩碗',
    '牛扒晚餐——200克西冷，薯蓉，沙律',
    '生果拼盤：西瓜、芒果、火龍果',
    '宵夜：梳打餅乾同鷹嘴豆泥',
  ],
  'zh-TW': [
    '午餐吃了叉燒飯和一杯冰奶茶',
    '早餐：兩顆荷包蛋、一片吐司、一杯柳橙汁',
    '吃了一點炒飯，大概半碗左右',
    '晚餐是一碗叉燒拉麵，有溏心蛋',
    '麥當勞雙層起司漢堡、中薯條、可樂',
    '吃了大概三貫壽司和一碗味噌湯',
    '點心：一根香蕉和一小把杏仁',
    '雞腿便當，一份',
    '自煮義大利麵加番茄醬，一人份',
    '晚餐吃了兩片辣腸披薩',
    '綠拿鐵——菠菜、香蕉、杏仁奶、蛋白粉',
    '下午茶：希臘優格加格蘭諾拉麥片和藍莓',
    '烤鮭魚配蒸花椰菜和白飯',
    '只喝了一杯燕麥拿鐵，沒有吃東西',
    '吃了三個叉燒包和一杯茉莉花茶',
    '泡麵加了一顆蛋和一些蔬菜',
    '韓式石鍋拌飯，有牛肉和各種蔬菜',
    '酪梨吐司加一顆水波蛋，全麥麵包',
    '珍珠奶茶——芋頭口味，半糖，去冰，大杯',
    '外賣炸魚薯條，吃了大部分',
    '健身後吃了一條蛋白棒',
    '皮蛋瘦肉粥，吃了兩碗',
    '牛排晚餐——200克沙朗，薯泥，沙拉',
    '水果拼盤：西瓜、芒果、火龍果',
    '宵夜：蘇打餅乾和鷹嘴豆泥',
  ],
}

export function getRandomAiPlaceholder(language) {
  const pool = AI_PLACEHOLDER_POOL[language] ?? AI_PLACEHOLDER_POOL.en
  return pool[Math.floor(Math.random() * pool.length)]
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }
  return context
}

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState('en')

  useEffect(() => {
    const saved = localStorage.getItem('recallth_language')
    if (saved && TRANSLATIONS[saved]) {
      setLanguageState(saved)
    }
  }, [])

  const setLanguage = (lang) => {
    if (TRANSLATIONS[lang]) {
      setLanguageState(lang)
      localStorage.setItem('recallth_language', lang)
    }
  }

  const t = (key, ...args) => {
    const strings = TRANSLATIONS[language] || TRANSLATIONS.en
    const value = strings[key] ?? TRANSLATIONS.en[key] ?? key
    return typeof value === 'function' ? value(...args) : value
  }

  const getDisplayName = () => {
    const names = { en: 'English', 'zh-TW': '繁體中文', 'zh-HK': '廣東話' }
    return names[language] || 'English'
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, getDisplayName, t }}>
      {children}
    </LanguageContext.Provider>
  )
}
