import { createContext, useContext, useState, useEffect } from 'react'

const TRANSLATIONS = {
  en: {
    // ── Nav ──────────────────────────────────────────────────────────────
    home: 'Home',
    chat: 'Chat',
    cabinet: 'Cabinet',
    profile: 'Profile',
    history: 'History',
    schedule: 'Schedule',
    stackBuilder: 'Stack Builder',
    doctorPrep: 'Doctor Prep',
    sideEffects: 'Side Effects',
    journal: 'Journal',
    progress: 'Progress',
    goals: 'Goals',
    notifications: 'Notifications',
    freePlan: 'Free plan',
    // ── Greetings ────────────────────────────────────────────────────────
    goodMorning: 'Good morning',
    goodAfternoon: 'Good afternoon',
    goodEvening: 'Good evening',
    // ── Home screen ──────────────────────────────────────────────────────
    locale: 'en-GB',
    statsSupplements: 'Supplements',
    statsConflicts: 'Conflicts',
    statsStreak: 'Streak',
    statsPowered: 'Powered',
    todaySchedule: "Today's schedule",
    noScheduleYet: 'No schedule yet.',
    addSuppsForSchedule: 'Add supplements to see your schedule',
    askAI: 'Ask Recallth AI',
    askAISubtitle: 'I remember your full health profile',
    askPlaceholder: 'Ask about supplements, dosing, interactions…',
    quickPrompt1: 'Should I take D3 with food?',
    quickPrompt2: 'Check my interactions',
    quickPrompt3: 'Best time for magnesium?',
    recentConversations: 'Recent conversations',
    noConversationsYet: 'No conversations yet.',
    startFirstChat: 'Start your first chat',
    conversationFallback: 'Conversation',
    viewAllConversations: 'View all conversations →',
    // ── Cabinet screen ───────────────────────────────────────────────────
    cabinetTitle: 'Cabinet',
    addSupplement: 'Add supplement',
    searchPlaceholder: 'Search supplements...',
    cabinetEmpty: 'Your cabinet is empty.',
    cabinetEmptySub: 'Add your first supplement.',
    noResults: 'No supplements match your search.',
    interactionWarning: (n) => `${n} interaction${n !== 1 ? 's' : ''} detected in your cabinet`,
    // ── Cabinet Add ──────────────────────────────────────────────────────
    addTitle: 'Add Supplement',
    addSubtitle: 'Track a new item',
    addButton: 'Add to cabinet',
    adding: 'Adding...',
    // ── Cabinet Detail ───────────────────────────────────────────────────
    editButton: 'Edit',
    saveButton: 'Save',
    saving: 'Saving...',
    cancelButton: 'Cancel',
    deleteButton: 'Delete supplement',
    deleting: 'Deleting...',
    confirmDelete: 'Delete this supplement?',
    cannotUndo: 'This action cannot be undone.',
    // ── Form field labels ────────────────────────────────────────────────
    fieldName: 'Name',
    fieldType: 'Type',
    fieldDosage: 'Dosage',
    fieldFrequency: 'Frequency',
    fieldTiming: 'Timing',
    fieldBrand: 'Brand (optional)',
    fieldNotes: 'Notes (optional)',
    // ── History screen ───────────────────────────────────────────────────
    historyTitle: 'History',
    historySub: (n) => `${n} conversation${n !== 1 ? 's' : ''}`,
    noConversationsTitle: 'No conversations yet',
    startConversation: 'Start a conversation',
    noConversationsMatch: 'No conversations match your search.',
    searchConversations: 'Search conversations...',
    // ── Chat ─────────────────────────────────────────────────────────────
    chatGreeting: (name) => `${name} 👋`,
    goodMorningGreet: 'Good morning',
    newChat: 'New chat',
    tapSuggestion: 'Tap a suggestion or ask anything...',
    stackReview: 'Stack review',
    todayPlan: "Today's plan",
    // ── Profile ──────────────────────────────────────────────────────────
    aboutMe: 'About me',
    goalsSection: 'Goals',
    exerciseSection: 'Exercise',
    dietSection: 'Diet',
    sleepSection: 'Sleep',
    lifestyleSection: 'Lifestyle',
    savingEllipsis: 'Saving…',
    failedToSave: 'Failed to save — try again',
    profileHistory: 'History',
    profileSchedule: 'Schedule',
    profileDashboard: 'Dashboard',
    fieldAge: 'Age',
    fieldHeight: 'Height',
    fieldWeight: 'Weight',
    fieldGender: 'Gender',
    fieldPrimaryGoal: 'Primary goal',
    fieldGoalsList: 'Goals (comma separated)',
    fieldFitnessLevel: 'Fitness level',
    fieldRestrictions: 'Restrictions (comma separated)',
    fieldAllergies: 'Allergies (comma separated)',
    fieldHoursPerNight: 'Hours per night',
    fieldIssues: 'Issues (comma separated)',
    fieldStressLevel: 'Stress level',
    fieldSmokingStatus: 'Smoking status',
    fieldAlcohol: 'Alcohol consumption',
    language: 'Language',
    logOut: 'Log out',
    // ── Goals screen ─────────────────────────────────────────────────────
    goalsSubtitle: 'Track your weekly wellbeing goals',
    goalsLogTitle: 'Log this week',
    goalsNameLabel: 'Goal name',
    goalsNamePlaceholder: 'e.g. Better sleep, More energy',
    goalsRatingLabel: 'How did it go?',
    goalsSubmit: 'Log this week',
    goalsSubmitting: 'Logging…',
    goalsNudgeTitle: 'AI insight',
    goalsEmpty: 'Log your first weekly check-in above to start tracking',
    goalsTrend: 'vs last week',
    goalsWeeks: 'Last 8 weeks',
    goalsNameRequired: 'Please enter a goal name',
    goalsRatingRequired: 'Please select a rating',
    goalsSubmitError: 'Failed to log — please try again',
    // ── Nutrition Tracker ────────────────────────────────────────────────
    nutritionTitle: 'Nutrition Tracker',
    nutritionSub: 'Track your daily nutrients',
    nutritionCalories: 'Calories',
    nutritionProtein: 'Protein',
    nutritionCarbs: 'Carbs',
    nutritionFat: 'Fat',
    nutritionMealBreakfast: 'Breakfast',
    nutritionMealLunch: 'Lunch',
    nutritionMealDinner: 'Dinner',
    nutritionMealSnack: 'Snack',
    nutritionAddTitle: 'Log Food',
    nutritionFieldFood: 'Food name',
    nutritionFieldQuantity: 'Quantity',
    nutritionFieldMeal: 'Meal',
    nutritionEmpty: 'No entries yet',
    nutritionEmptySub: 'Log your first meal',
    nutritionDeleteConfirm: 'Delete this entry?',
    // ── Common ───────────────────────────────────────────────────────────
    back: 'Back',
  },

  'zh-TW': {
    home: '主頁',
    chat: '對話',
    cabinet: '藥箱',
    profile: '個人',
    history: '歷史記錄',
    schedule: '排程',
    stackBuilder: '堆疊配方',
    doctorPrep: '醫師準備',
    sideEffects: '副作用',
    journal: '日誌',
    progress: '進度',
    goals: '目標',
    notifications: '通知設定',
    freePlan: '免費方案',
    goodMorning: '早安',
    goodAfternoon: '午安',
    goodEvening: '晚安',
    locale: 'zh-TW',
    statsSupplements: '補充品',
    statsConflicts: '衝突',
    statsStreak: '連續天數',
    statsPowered: 'AI 驅動',
    todaySchedule: '今日排程',
    noScheduleYet: '尚無排程。',
    addSuppsForSchedule: '新增補充品以查看排程',
    askAI: '詢問 Recallth AI',
    askAISubtitle: '我記得您的完整健康資料',
    askPlaceholder: '詢問補充品、劑量、交互作用…',
    quickPrompt1: '維生素D3需要與食物一起服用嗎？',
    quickPrompt2: '查看我的交互作用',
    quickPrompt3: '鎂的最佳服用時機？',
    recentConversations: '近期對話',
    noConversationsYet: '尚無對話。',
    startFirstChat: '開始第一個對話',
    conversationFallback: '對話',
    viewAllConversations: '查看所有對話 →',
    cabinetTitle: '藥箱',
    addSupplement: '新增補充品',
    searchPlaceholder: '搜尋補充品...',
    cabinetEmpty: '藥箱是空的。',
    cabinetEmptySub: '新增您的第一個補充品。',
    noResults: '找不到符合的補充品。',
    interactionWarning: (n) => `您的藥箱中偵測到 ${n} 個交互作用`,
    addTitle: '新增補充品',
    addSubtitle: '追蹤新項目',
    addButton: '加入藥箱',
    adding: '新增中...',
    editButton: '編輯',
    saveButton: '儲存',
    saving: '儲存中...',
    cancelButton: '取消',
    deleteButton: '刪除補充品',
    deleting: '刪除中...',
    confirmDelete: '確定要刪除此補充品？',
    cannotUndo: '此操作無法復原。',
    fieldName: '名稱',
    fieldType: '類型',
    fieldDosage: '劑量',
    fieldFrequency: '頻率',
    fieldTiming: '時機',
    fieldBrand: '品牌（選填）',
    fieldNotes: '備注（選填）',
    historyTitle: '歷史記錄',
    historySub: (n) => `${n} 個對話`,
    noConversationsTitle: '尚無對話',
    startConversation: '開始對話',
    noConversationsMatch: '找不到符合的對話。',
    searchConversations: '搜尋對話...',
    chatGreeting: (name) => `${name} 👋`,
    goodMorningGreet: '早安',
    newChat: '新對話',
    tapSuggestion: '點選建議或輸入問題...',
    stackReview: '堆疊審查',
    todayPlan: '今日計劃',
    aboutMe: '關於我',
    goalsSection: '目標',
    exerciseSection: '運動',
    dietSection: '飲食',
    sleepSection: '睡眠',
    lifestyleSection: '生活方式',
    savingEllipsis: '儲存中…',
    failedToSave: '儲存失敗 — 請再試一次',
    profileHistory: '歷史記錄',
    profileSchedule: '排程',
    profileDashboard: '儀表板',
    fieldAge: '年齡',
    fieldHeight: '身高',
    fieldWeight: '體重',
    fieldGender: '性別',
    fieldPrimaryGoal: '主要目標',
    fieldGoalsList: '目標（以逗號分隔）',
    fieldFitnessLevel: '健身程度',
    fieldRestrictions: '飲食限制（以逗號分隔）',
    fieldAllergies: '過敏症（以逗號分隔）',
    fieldHoursPerNight: '每晚睡眠時數',
    fieldIssues: '睡眠問題（以逗號分隔）',
    fieldStressLevel: '壓力程度',
    fieldSmokingStatus: '吸煙狀況',
    fieldAlcohol: '酒精攝取',
    language: '語言',
    logOut: '登出',
    goalsSubtitle: '追蹤您每週的健康目標',
    goalsLogTitle: '記錄本週',
    goalsNameLabel: '目標名稱',
    goalsNamePlaceholder: '例如：更好的睡眠、更多能量',
    goalsRatingLabel: '本週表現如何？',
    goalsSubmit: '記錄本週',
    goalsSubmitting: '記錄中…',
    goalsNudgeTitle: 'AI 建議',
    goalsEmpty: '在上方記錄您的第一次每週打卡以開始追蹤',
    goalsTrend: '與上週相比',
    goalsWeeks: '近 8 週',
    goalsNameRequired: '請輸入目標名稱',
    goalsRatingRequired: '請選擇評分',
    goalsSubmitError: '記錄失敗 — 請再試一次',
    // ── Nutrition Tracker ────────────────────────────────────────────────
    nutritionTitle: '營養追蹤',
    nutritionSub: '追蹤每日營養攝取',
    nutritionCalories: '卡路里',
    nutritionProtein: '蛋白質',
    nutritionCarbs: '碳水化合物',
    nutritionFat: '脂肪',
    nutritionMealBreakfast: '早餐',
    nutritionMealLunch: '午餐',
    nutritionMealDinner: '晚餐',
    nutritionMealSnack: '小食',
    nutritionAddTitle: '記錄食物',
    nutritionFieldFood: '食物名稱',
    nutritionFieldQuantity: '份量',
    nutritionFieldMeal: '餐別',
    nutritionEmpty: '還沒有記錄',
    nutritionEmptySub: '記錄你今天吃了什麼',
    nutritionDeleteConfirm: '確定刪除此記錄？',
    back: '返回',
  },

  'zh-HK': {
    home: '主頁',
    chat: '對話',
    cabinet: '藥箱',
    profile: '個人',
    history: '歷史記錄',
    schedule: '時間表',
    stackBuilder: '配方搭配',
    doctorPrep: '醫生準備',
    sideEffects: '副作用',
    journal: '日誌',
    progress: '進度',
    goals: '目標',
    notifications: '通知設定',
    freePlan: '免費計劃',
    goodMorning: '早晨',
    goodAfternoon: '午安',
    goodEvening: '晚安',
    locale: 'zh-HK',
    statsSupplements: '補充品',
    statsConflicts: '衝突',
    statsStreak: '連續打卡',
    statsPowered: 'AI 支援',
    todaySchedule: '今日時間表',
    noScheduleYet: '未有時間表。',
    addSuppsForSchedule: '加補充品先睇到時間表',
    askAI: '問 Recallth AI',
    askAISubtitle: '我記住曬你嘅健康資料',
    askPlaceholder: '問補充品、劑量、交互作用…',
    quickPrompt1: '食D3要唔要同食物一齊食？',
    quickPrompt2: '查我嘅交互作用',
    quickPrompt3: '鎂最好幾時食？',
    recentConversations: '最近對話',
    noConversationsYet: '未有對話。',
    startFirstChat: '開始第一個對話',
    conversationFallback: '對話',
    viewAllConversations: '睇所有對話 →',
    cabinetTitle: '藥箱',
    addSupplement: '加補充品',
    searchPlaceholder: '搵補充品...',
    cabinetEmpty: '藥箱係空㗎。',
    cabinetEmptySub: '加你第一個補充品。',
    noResults: '搵唔到符合嘅補充品。',
    interactionWarning: (n) => `你嘅藥箱有 ${n} 個交互作用`,
    addTitle: '加補充品',
    addSubtitle: '追蹤新項目',
    addButton: '加入藥箱',
    adding: '加緊...',
    editButton: '編輯',
    saveButton: '儲存',
    saving: '儲存緊...',
    cancelButton: '取消',
    deleteButton: '刪除補充品',
    deleting: '刪緊...',
    confirmDelete: '確定要刪除呢個補充品？',
    cannotUndo: '呢個操作係冇得返轉頭㗎。',
    fieldName: '名稱',
    fieldType: '類型',
    fieldDosage: '劑量',
    fieldFrequency: '頻率',
    fieldTiming: '時機',
    fieldBrand: '品牌（可選）',
    fieldNotes: '備注（可選）',
    historyTitle: '歷史記錄',
    historySub: (n) => `${n} 個對話`,
    noConversationsTitle: '未有對話',
    startConversation: '開始對話',
    noConversationsMatch: '搵唔到符合嘅對話。',
    searchConversations: '搵對話...',
    chatGreeting: (name) => `${name} 👋`,
    goodMorningGreet: '早晨',
    newChat: '新對話',
    tapSuggestion: '撳建議或者問任何野...',
    stackReview: '堆疊審查',
    todayPlan: '今日計劃',
    aboutMe: '關於我',
    goalsSection: '目標',
    exerciseSection: '運動',
    dietSection: '飲食',
    sleepSection: '睡眠',
    lifestyleSection: '生活方式',
    savingEllipsis: '儲存緊…',
    failedToSave: '儲存失敗 — 再試一次',
    profileHistory: '歷史記錄',
    profileSchedule: '時間表',
    profileDashboard: '主頁',
    fieldAge: '年齡',
    fieldHeight: '身高',
    fieldWeight: '體重',
    fieldGender: '性別',
    fieldPrimaryGoal: '主要目標',
    fieldGoalsList: '目標（以逗號分隔）',
    fieldFitnessLevel: '健身水平',
    fieldRestrictions: '飲食限制（以逗號分隔）',
    fieldAllergies: '敏感症（以逗號分隔）',
    fieldHoursPerNight: '每晚睡眠時數',
    fieldIssues: '睡眠問題（以逗號分隔）',
    fieldStressLevel: '壓力程度',
    fieldSmokingStatus: '吸煙狀況',
    fieldAlcohol: '飲酒情況',
    language: '語言',
    logOut: '登出',
    goalsSubtitle: '追蹤你每週嘅健康目標',
    goalsLogTitle: '記錄本週',
    goalsNameLabel: '目標名稱',
    goalsNamePlaceholder: '例如：瞓好啲、精力多啲',
    goalsRatingLabel: '今週表現點？',
    goalsSubmit: '記錄本週',
    goalsSubmitting: '記錄緊…',
    goalsNudgeTitle: 'AI 建議',
    goalsEmpty: '喺上面記錄你第一次每週打卡，開始追蹤',
    goalsTrend: '對比上週',
    goalsWeeks: '近 8 週',
    goalsNameRequired: '請輸入目標名稱',
    goalsRatingRequired: '請選擇評分',
    goalsSubmitError: '記錄失敗 — 請再試一次',
    // ── Nutrition Tracker ────────────────────────────────────────────────
    nutritionTitle: '營養追蹤',
    nutritionSub: '追蹤每日營養攝取',
    nutritionCalories: '卡路里',
    nutritionProtein: '蛋白質',
    nutritionCarbs: '碳水',
    nutritionFat: '脂肪',
    nutritionMealBreakfast: '早餐',
    nutritionMealLunch: '午餐',
    nutritionMealDinner: '晚餐',
    nutritionMealSnack: '小食',
    nutritionAddTitle: '記錄食物',
    nutritionFieldFood: '食物名稱',
    nutritionFieldQuantity: '份量',
    nutritionFieldMeal: '餐別',
    nutritionEmpty: '未有記錄',
    nutritionEmptySub: '記錄你今日食咗咩',
    nutritionDeleteConfirm: '確定刪除呢條記錄？',
    back: '返回',
  },
}

const LanguageContext = createContext()

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }
  return context
}

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState('en')

  useEffect(() => {
    const saved = localStorage.getItem('recallth_language')
    if (saved && TRANSLATIONS[saved]) {
      setLanguageState(saved)
    }
  }, [])

  const setLanguage = (lang) => {
    if (TRANSLATIONS[lang]) {
      setLanguageState(lang)
      localStorage.setItem('recallth_language', lang)
    }
  }

  const t = (key, ...args) => {
    const strings = TRANSLATIONS[language] || TRANSLATIONS.en
    const value = strings[key] ?? TRANSLATIONS.en[key] ?? key
    return typeof value === 'function' ? value(...args) : value
  }

  const getDisplayName = () => {
    const names = { en: 'English', 'zh-TW': '繁體中文', 'zh-HK': '廣東話' }
    return names[language] || 'English'
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, getDisplayName, t }}>
      {children}
    </LanguageContext.Provider>
  )
}
