import { createContext, useContext, useState, useEffect } from 'react'

const TRANSLATIONS = {
  en: {
    // ── Nav ──────────────────────────────────────────────────────────────
    home: 'Home',
    chat: 'Chat',
    cabinet: 'Cabinet',
    profile: 'Profile',
    history: 'History',
    schedule: 'Schedule',
    stackBuilder: 'Stack Builder',
    doctorPrep: 'Doctor Prep',
    sideEffects: 'Side Effects',
    journal: 'Journal',
    progress: 'Progress',
    goals: 'Goals',
    notifications: 'Notifications',
    freePlan: 'Free plan',
    // ── Greetings ────────────────────────────────────────────────────────
    goodMorning: 'Good morning',
    goodAfternoon: 'Good afternoon',
    goodEvening: 'Good evening',
    // ── Home screen ──────────────────────────────────────────────────────
    locale: 'en-GB',
    statsSupplements: 'Supplements',
    statsConflicts: 'Conflicts',
    statsStreak: 'Streak',
    statsPowered: 'Powered',
    todaySchedule: "Today's schedule",
    noScheduleYet: 'No schedule yet.',
    addSuppsForSchedule: 'Add supplements to see your schedule',
    askAI: 'Ask Recallth AI',
    askAISubtitle: 'I remember your full health profile',
    askPlaceholder: 'Ask about supplements, dosing, interactions…',
    quickPrompt1: 'Should I take D3 with food?',
    quickPrompt2: 'Check my interactions',
    quickPrompt3: 'Best time for magnesium?',
    recentConversations: 'Recent conversations',
    noConversationsYet: 'No conversations yet.',
    startFirstChat: 'Start your first chat',
    conversationFallback: 'Conversation',
    viewAllConversations: 'View all conversations →',
    // ── Cabinet screen ───────────────────────────────────────────────────
    cabinetTitle: 'Cabinet',
    addSupplement: 'Add supplement',
    searchPlaceholder: 'Search supplements...',
    cabinetEmpty: 'Your cabinet is empty.',
    cabinetEmptySub: 'Add your first supplement.',
    noResults: 'No supplements match your search.',
    recent: 'Recent',
    interactionWarning: (n) => `${n} interaction${n !== 1 ? 's' : ''} detected in your cabinet`,
    // ── Cabinet Add ──────────────────────────────────────────────────────
    addTitle: 'Add Supplement',
    addSubtitle: 'Track a new item',
    addButton: 'Add to cabinet',
    adding: 'Adding...',
    // ── Cabinet Detail ───────────────────────────────────────────────────
    editButton: 'Edit',
    saveButton: 'Save',
    saving: 'Saving...',
    cancelButton: 'Cancel',
    deleteButton: 'Delete supplement',
    deleting: 'Deleting...',
    confirmDelete: 'Delete this supplement?',
    cannotUndo: 'This action cannot be undone.',
    // ── Form field labels ────────────────────────────────────────────────
    fieldName: 'Name',
    fieldType: 'Type',
    fieldDosage: 'Dosage',
    fieldFrequency: 'Frequency',
    fieldTiming: 'Timing',
    fieldBrand: 'Brand (optional)',
    fieldNotes: 'Notes (optional)',
    fieldDescription: 'Description',
    fieldIngredients: 'Ingredients',
    uploadPhoto: 'Upload photo',
    changePhoto: 'Change photo',
    uploading: 'Uploading...',
    imageTooLarge: 'Image must be under 2MB',
    aiLookupButton: 'AI Auto-fill product info',
    aiLookupTitle: 'AI Product Lookup',
    aiLookupHint: 'Type a product name (e.g. "PVL Whey Gold chocolate") and AI will fill in all the details.',
    aiLookupPlaceholder: 'e.g. NOW Foods Magnesium 400mg',
    aiLookupSearch: 'Search',
    aiLookupSearching: 'Searching...',
    aiLookupClear: 'Clear',
    aiLookupConfirmTitle: 'Is this the right product?',
    aiLookupConfirm: 'Yes, fill it in',
    aiLookupRetry: 'Try again',
    aiLookupFilled: 'Product info filled by AI',
    aiLookupUndo: 'Undo',
    // ── History screen ───────────────────────────────────────────────────
    historyTitle: 'History',
    historySub: (n) => `${n} conversation${n !== 1 ? 's' : ''}`,
    noConversationsTitle: 'No conversations yet',
    startConversation: 'Start a conversation',
    noConversationsMatch: 'No conversations match your search.',
    searchConversations: 'Search conversations...',
    // ── Chat ─────────────────────────────────────────────────────────────
    chatGreeting: (name) => `${name} 👋`,
    goodMorningGreet: 'Good morning',
    newChat: 'New chat',
    tapSuggestion: 'Tap a suggestion or ask anything...',
    stackReview: 'Stack review',
    todayPlan: "Today's plan",
    chatTitle: 'Recallth AI',
    chatHeaderActive: 'Chat',
    chatHowCanHelp: 'How can I help with your stack today?',
    chatSugg1: 'My stack today',
    chatSugg2: 'Interactions?',
    chatSugg3: 'Best timing',
    chatSugg4: 'Pre-workout plan',
    chatSugg5: 'Sleep supplements',
    chatSugg6: 'Evidence check',
    chatRecent: 'Recent',
    chatViewAll: 'View all',
    chatConversations: 'Conversations',
    chatSearch: 'Search...',
    chatNoConvos: 'No conversations yet',
    chatNoMatches: 'No matches',
    chatFollowUp: 'Follow up...',
    chatAskAnything: 'Ask anything about your supplements...',
    chatSentImage: 'Sent an image',
    chatImagePrompt: 'What is this supplement?',
    chatNoResponse: 'No response',
    chatError: 'Something went wrong. Please try again.',
    chatQuickActions: 'Quick actions',
    chatJustNow: 'Just now',
    chatYesterday: 'Yesterday',
    // ── Profile ──────────────────────────────────────────────────────────
    aboutMe: 'About me',
    goalsSection: 'Goals',
    exerciseSection: 'Exercise',
    dietSection: 'Diet',
    sleepSection: 'Sleep',
    lifestyleSection: 'Lifestyle',
    savingEllipsis: 'Saving…',
    failedToSave: 'Failed to save — try again',
    profileHistory: 'History',
    profileSchedule: 'Schedule',
    profileDashboard: 'Dashboard',
    fieldAge: 'Age',
    fieldHeight: 'Height',
    fieldWeight: 'Weight',
    fieldGender: 'Gender',
    fieldPrimaryGoal: 'Primary goal',
    fieldGoalsList: 'Goals (comma separated)',
    fieldFitnessLevel: 'Fitness level',
    fieldRestrictions: 'Restrictions (comma separated)',
    fieldAllergies: 'Allergies (comma separated)',
    fieldHoursPerNight: 'Hours per night',
    fieldIssues: 'Issues (comma separated)',
    fieldStressLevel: 'Stress level',
    fieldSmokingStatus: 'Smoking status',
    fieldAlcohol: 'Alcohol consumption',
    language: 'Language',
    logOut: 'Log out',
    // ── Goals screen ─────────────────────────────────────────────────────
    goalsSubtitle: 'Track your weekly wellbeing goals',
    goalsLogTitle: 'Log this week',
    goalsNameLabel: 'Goal name',
    goalsNamePlaceholder: 'e.g. Better sleep, More energy',
    goalsRatingLabel: 'How did it go?',
    goalsSubmit: 'Log this week',
    goalsSubmitting: 'Logging…',
    goalsNudgeTitle: 'AI insight',
    goalsEmpty: 'Log your first weekly check-in above to start tracking',
    goalsTrend: 'vs last week',
    goalsWeeks: 'Last 8 weeks',
    goalsNameRequired: 'Please enter a goal name',
    goalsRatingRequired: 'Please select a rating',
    goalsSubmitError: 'Failed to log — please try again',
    // ── Auth ────────────────────────────────────────────────────────────
    authWelcome: 'Welcome back',
    authGetStarted: 'Get started',
    authSignInSub: 'Sign in to your account',
    authCreateSub: 'Create your free account',
    authSignUp: 'Sign up',
    authLogIn: 'Log in',
    authContinueGoogle: 'Continue with Google',
    authComingSoon: 'Coming soon',
    authOr: 'or',
    authName: 'Name',
    authNamePlaceholder: 'Your name',
    authEmail: 'Email',
    authEmailPlaceholder: 'you@example.com',
    authPassword: 'Password',
    authPasswordPlaceholder: 'Min. 8 characters',
    authPasswordPlaceholderLogin: 'Your password',
    authPleaseWait: 'Please wait…',
    authCreateAccount: 'Create account',
    authNoAccount: "Don't have an account? ",
    authHaveAccount: 'Already have an account? ',
    // ── Schedule screen ─────────────────────────────────────────────────
    scheduleTitle: 'Schedule',
    scheduleEmpty: 'No schedule yet',
    scheduleEmptySub: 'Add supplements to your cabinet to generate a schedule',
    scheduleGoToCabinet: 'Go to Cabinet',
    slotMorning: 'Morning',
    slotAfternoon: 'Afternoon',
    slotEvening: 'Evening',
    slotNight: 'Night',
    slotAnytime: 'Anytime',
    // ── Journal ─────────────────────────────────────────────────────────
    journalTitle: 'Journal',
    journalSub: 'Track how you feel each day',
    journalLogToday: 'Log today',
    journalMood: 'Mood',
    journalEnergy: 'Energy',
    journalNotesPlaceholder: 'How are you feeling?',
    journalSubmit: 'Log Entry',
    journalSave: 'Save',
    journalNoEntries: 'No entries yet',
    journalNoEntriesSub: 'Log your first entry above to get started',
    journalDeleteConfirm: 'Delete this entry?',
    journalDelete: 'Delete',
    // ── Side Effects ────────────────────────────────────────────────────
    sideEffectsTitle: 'Side Effects',
    sideEffectsSub: 'Track how supplements affect you over time',
    sideEffectsLog: 'Log a side effect',
    sideEffectsSupplement: 'Supplement',
    sideEffectsSelectSupp: 'Select supplement…',
    sideEffectsSuppPlaceholder: 'Supplement name',
    sideEffectsWhat: 'What did you notice?',
    sideEffectsWhatPlaceholder: 'What did you notice?',
    sideEffectsSeverity: 'Severity',
    sideEffectsMild: 'Mild',
    sideEffectsModerate: 'Moderate',
    sideEffectsSevere: 'Severe',
    sideEffectsDate: 'Date',
    sideEffectsSubmit: 'Log Effect',
    sideEffectsLogging: 'Logging…',
    sideEffectsHistory: 'History',
    sideEffectsEmpty: 'No side effects logged — track how supplements affect you',
    sideEffectsDeleteConfirm: 'Are you sure?',
    sideEffectsYes: 'Yes',
    sideEffectsNo: 'No',
    // ── Progress ────────────────────────────────────────────────────────
    progressTitle: 'Progress',
    progressSub: 'Track your body stats over time',
    progressLogStats: 'Log Stats',
    progressWeight: 'Weight (kg)',
    progressBodyFat: 'Body fat %',
    progressDate: 'Date',
    progressNotes: 'Notes',
    progressOptional: 'optional',
    progressLogging: 'Logging…',
    progressWeightPlaceholder: 'e.g. 72.5',
    progressKgNow: 'kg now',
    progressChange: 'change',
    progressEntries: 'entries',
    progressWeightTrend: 'Weight trend (kg)',
    progressBfTrend: 'Body fat trend (%)',
    progressAllEntries: 'All entries',
    progressEmpty: 'No stats yet — log your first measurement',
    progressEmptySub: 'Use the form above to get started.',
    progressBodyFatLabel: '% body fat',
    progressWeightRequired: 'Weight is required.',
    progressFailed: 'Failed to log stats — try again.',
    // ── Bloodwork ───────────────────────────────────────────────────────
    bloodworkTitle: 'Bloodwork',
    bloodworkSub: 'Track your lab results over time',
    bloodworkLogNew: 'Log new results',
    bloodworkTestDate: 'Test date',
    bloodworkQuickAdd: 'Quick add',
    bloodworkCustomMarker: 'Custom marker',
    bloodworkUnit: 'Unit',
    bloodworkAdd: 'Add',
    bloodworkValue: 'Value',
    bloodworkSaving: 'Saving…',
    bloodworkLogResults: 'Log Results',
    bloodworkAnalysing: 'Analysing…',
    bloodworkGetAI: 'Get AI interpretation',
    bloodworkInterpretFailed: 'Interpretation failed — try again',
    bloodworkEmpty: 'No bloodwork logged',
    bloodworkEmptySub: 'Add markers above to track your lab results',
    bloodworkInRange: 'In range',
    bloodworkBelow: 'Below range',
    bloodworkAbove: 'Above range',
    bloodworkMarker: 'marker',
    bloodworkMarkers: 'markers',
    // ── Doctor Prep ─────────────────────────────────────────────────────
    doctorPrepTitle: 'Doctor Prep',
    doctorPrepSub: 'Questions to ask at your next appointment',
    doctorPrepGenerating: 'Generating your questions…',
    doctorPrepFailed: "Couldn't generate questions",
    doctorPrepFailedSub: 'Make sure your cabinet and profile have some data, then try again.',
    doctorPrepRetry: 'Retry',
    doctorPrepReady: (n) => `${n} question${n !== 1 ? 's' : ''} ready`,
    doctorPrepCopied: 'Copied!',
    doctorPrepCopyAll: 'Copy all',
    // ── Stack Builder ───────────────────────────────────────────────────
    stackBuilderTitle: 'Stack Builder',
    stackBuilderSub: 'Enter a health goal and get personalised supplement recommendations in seconds.',
    stackBuilderPlaceholder: 'e.g. better sleep, muscle building…',
    stackBuilderGenerate: 'Build Stack',
    stackBuilderGenerating: 'Generating…',
    stackBuilderEmpty: 'Build your personalised stack',
    stackBuilderEmptySub: "Type a health goal above — sleep, energy, performance, immunity — and we'll recommend the right supplements for you.",
    stackBuilderLoading: 'Generating your stack…',
    stackBuilderFailed: "Couldn't generate recommendations — try again",
    stackBuilderRetry: 'Retry',
    stackBuilderInStack: 'In your stack',
    stackBuilderAdded: 'Added',
    stackBuilderAddToStack: 'Add to stack',
    stackBuilderAdding: 'Adding…',
    stackBuilderEssential: 'Essential',
    stackBuilderBeneficial: 'Beneficial',
    stackBuilderOptional: 'Optional',
    // ── Notifications ───────────────────────────────────────────────────
    notificationsTitle: 'Notifications',
    notificationsSub: 'Manage reminders, digests and your timezone.',
    notificationsLoadError: 'Could not load settings — try refreshing',
    notificationsReminders: 'Daily supplement reminders',
    notificationsNoReminders: 'No reminders set. Add one below.',
    notificationsAddReminder: 'Add reminder',
    notificationsDigestTitle: 'Weekly digest email',
    notificationsDigestToggle: 'Email digest',
    notificationsDigestSub: 'Receive a weekly summary of your supplement activity',
    notificationsDigestDay: 'Send on',
    notificationsTimezone: 'Timezone',
    notificationsSaved: 'Saved',
    notificationsMon: 'Mon',
    notificationsTue: 'Tue',
    notificationsWed: 'Wed',
    notificationsThu: 'Thu',
    notificationsFri: 'Fri',
    notificationsSat: 'Sat',
    notificationsSun: 'Sun',
    // ── Onboarding ──────────────────────────────────────────────────────
    onboardingStep: (curr, total) => `Step ${curr} of ${total}`,
    onboardingGoalsTitle: 'What are your goals?',
    onboardingGoalsSub: 'Select all that apply',
    onboardingGoalMuscle: 'Muscle & strength',
    onboardingGoalRecovery: 'Recovery',
    onboardingGoalSleep: 'Better sleep',
    onboardingGoalEnergy: 'More energy',
    onboardingGoalHealth: 'General health',
    onboardingGoalWeight: 'Weight management',
    onboardingContinue: 'Continue',
    onboardingBack: 'Back',
    onboardingSuppTitle: 'Add your first supplement',
    onboardingSuppSub: 'You can add more from your cabinet later',
    onboardingSuppName: 'Supplement name',
    onboardingSuppNamePlaceholder: 'e.g. Creatine, Omega-3, Vitamin D',
    onboardingSuppDose: 'Dose',
    onboardingSuppDosePlaceholder: 'e.g. 5g, 1000mg, 2 capsules',
    onboardingSuppTiming: 'Timing',
    onboardingSuppSkip: 'Skip for now',
    onboardingSchedTitle: 'When do you prefer to dose?',
    onboardingSchedSub: 'We will optimise your schedule around this',
    onboardingSchedMorning: 'Morning-heavy',
    onboardingSchedMorningSub: 'Front-load your supplements before midday',
    onboardingSchedEvening: 'Evening-heavy',
    onboardingSchedEveningSub: 'Take most supplements in the afternoon and evening',
    onboardingFinish: 'Finish setup',
    // ── Evidence ────────────────────────────────────────────────────────
    evidenceStrong: 'Strong evidence',
    evidenceGood: 'Good evidence',
    evidenceModerate: 'Moderate evidence',
    evidenceLimited: 'Limited evidence',
    // ── Misc ────────────────────────────────────────────────────────────
    active: 'Active',
    conflicts: 'Conflicts',
    interactions: 'Interactions',
    failedToLoad: 'Failed to load',
    suppNotFound: 'Supplement not found',
    nameRequired: 'Name is required',
    dosageRequired: 'Dosage is required',
    failedToSaveChanges: 'Failed to save changes',
    failedToDelete: 'Failed to delete',
    failedToAdd: 'Failed to add supplement',
    failedToLoadHistory: 'Failed to load history',
    imageAttached: 'Image attached',
    searchEllipsis: 'Search or ask anything…',
    msgs: 'msgs',
    messages: 'messages',
    unknown: 'Unknown',
    supplement: 'Supplement',
    // ── Relative time ───────────────────────────────────────────────────
    timeMinAgo: (n) => `${n}m ago`,
    timeHrAgo: (n) => `${n}h ago`,
    timeDaysAgo: (n) => `${n}d ago`,
    timeYesterday: 'Yesterday',
    // ── Common ───────────────────────────────────────────────────────────
    back: 'Back',
  },

  'zh-TW': {
    home: '主頁',
    chat: '對話',
    cabinet: '藥箱',
    profile: '個人',
    history: '歷史記錄',
    schedule: '排程',
    stackBuilder: '堆疊配方',
    doctorPrep: '醫師準備',
    sideEffects: '副作用',
    journal: '日誌',
    progress: '進度',
    goals: '目標',
    notifications: '通知設定',
    freePlan: '免費方案',
    goodMorning: '早安',
    goodAfternoon: '午安',
    goodEvening: '晚安',
    locale: 'zh-TW',
    statsSupplements: '補充品',
    statsConflicts: '衝突',
    statsStreak: '連續天數',
    statsPowered: 'AI 驅動',
    todaySchedule: '今日排程',
    noScheduleYet: '尚無排程。',
    addSuppsForSchedule: '新增補充品以查看排程',
    askAI: '詢問 Recallth AI',
    askAISubtitle: '我記得您的完整健康資料',
    askPlaceholder: '詢問補充品、劑量、交互作用…',
    quickPrompt1: '維生素D3需要與食物一起服用嗎？',
    quickPrompt2: '查看我的交互作用',
    quickPrompt3: '鎂的最佳服用時機？',
    recentConversations: '近期對話',
    noConversationsYet: '尚無對話。',
    startFirstChat: '開始第一個對話',
    conversationFallback: '對話',
    viewAllConversations: '查看所有對話 →',
    cabinetTitle: '藥箱',
    addSupplement: '新增補充品',
    searchPlaceholder: '搜尋補充品...',
    cabinetEmpty: '藥箱是空的。',
    cabinetEmptySub: '新增您的第一個補充品。',
    noResults: '找不到符合的補充品。',
    recent: '最近',
    interactionWarning: (n) => `您的藥箱中偵測到 ${n} 個交互作用`,
    addTitle: '新增補充品',
    addSubtitle: '追蹤新項目',
    addButton: '加入藥箱',
    adding: '新增中...',
    editButton: '編輯',
    saveButton: '儲存',
    saving: '儲存中...',
    cancelButton: '取消',
    deleteButton: '刪除補充品',
    deleting: '刪除中...',
    confirmDelete: '確定要刪除此補充品？',
    cannotUndo: '此操作無法復原。',
    fieldName: '名稱',
    fieldType: '類型',
    fieldDosage: '劑量',
    fieldFrequency: '頻率',
    fieldTiming: '時機',
    fieldBrand: '品牌（選填）',
    fieldNotes: '備注（選填）',
    fieldDescription: '描述',
    fieldIngredients: '成份',
    uploadPhoto: '上傳照片',
    changePhoto: '更換照片',
    uploading: '上傳中...',
    imageTooLarge: '圖片須小於 2MB',
    aiLookupButton: 'AI 自動填入產品資訊',
    aiLookupTitle: 'AI 產品搜尋',
    aiLookupHint: '輸入產品名稱（例如「PVL Whey Gold 朱古力味」），AI 會自動填入所有資料。',
    aiLookupPlaceholder: '例如 NOW Foods 鎂 400mg',
    aiLookupSearch: '搜尋',
    aiLookupSearching: '搜尋中...',
    aiLookupClear: '清除',
    aiLookupConfirmTitle: '係唔係呢隻產品？',
    aiLookupConfirm: '確認填入',
    aiLookupRetry: '重新搜尋',
    aiLookupFilled: '已由 AI 填入產品資料',
    aiLookupUndo: '復原',
    historyTitle: '歷史記錄',
    historySub: (n) => `${n} 個對話`,
    noConversationsTitle: '尚無對話',
    startConversation: '開始對話',
    noConversationsMatch: '找不到符合的對話。',
    searchConversations: '搜尋對話...',
    chatGreeting: (name) => `${name} 👋`,
    goodMorningGreet: '早安',
    newChat: '新對話',
    tapSuggestion: '點選建議或輸入問題...',
    stackReview: '堆疊審查',
    todayPlan: '今日計劃',
    chatTitle: 'Recallth AI',
    chatHeaderActive: '對話',
    chatHowCanHelp: '今日有咩可以幫到你？',
    chatSugg1: '我今日嘅補充品',
    chatSugg2: '有冇交互作用？',
    chatSugg3: '最佳服用時間',
    chatSugg4: '健身前計劃',
    chatSugg5: '助眠補充品',
    chatSugg6: '科學證據',
    chatRecent: '最近',
    chatViewAll: '查看全部',
    chatConversations: '對話記錄',
    chatSearch: '搜尋...',
    chatNoConvos: '暫無對話',
    chatNoMatches: '找不到結果',
    chatFollowUp: '繼續問...',
    chatAskAnything: '問任何關於補充品嘅問題...',
    chatSentImage: '已傳送圖片',
    chatImagePrompt: '呢個係咩補充品？',
    chatNoResponse: '無回應',
    chatError: '出錯了，請再試一次。',
    chatQuickActions: '快捷操作',
    chatJustNow: '剛剛',
    chatYesterday: '昨天',
    aboutMe: '關於我',
    goalsSection: '目標',
    exerciseSection: '運動',
    dietSection: '飲食',
    sleepSection: '睡眠',
    lifestyleSection: '生活方式',
    savingEllipsis: '儲存中…',
    failedToSave: '儲存失敗 — 請再試一次',
    profileHistory: '歷史記錄',
    profileSchedule: '排程',
    profileDashboard: '儀表板',
    fieldAge: '年齡',
    fieldHeight: '身高',
    fieldWeight: '體重',
    fieldGender: '性別',
    fieldPrimaryGoal: '主要目標',
    fieldGoalsList: '目標（以逗號分隔）',
    fieldFitnessLevel: '健身程度',
    fieldRestrictions: '飲食限制（以逗號分隔）',
    fieldAllergies: '過敏症（以逗號分隔）',
    fieldHoursPerNight: '每晚睡眠時數',
    fieldIssues: '睡眠問題（以逗號分隔）',
    fieldStressLevel: '壓力程度',
    fieldSmokingStatus: '吸煙狀況',
    fieldAlcohol: '酒精攝取',
    language: '語言',
    logOut: '登出',
    goalsSubtitle: '追蹤您每週的健康目標',
    goalsLogTitle: '記錄本週',
    goalsNameLabel: '目標名稱',
    goalsNamePlaceholder: '例如：更好的睡眠、更多能量',
    goalsRatingLabel: '本週表現如何？',
    goalsSubmit: '記錄本週',
    goalsSubmitting: '記錄中…',
    goalsNudgeTitle: 'AI 建議',
    goalsEmpty: '在上方記錄您的第一次每週打卡以開始追蹤',
    goalsTrend: '與上週相比',
    goalsWeeks: '近 8 週',
    goalsNameRequired: '請輸入目標名稱',
    goalsRatingRequired: '請選擇評分',
    goalsSubmitError: '記錄失敗 — 請再試一次',
    // ── Auth ────────────────────────────────────────────────────────────
    authWelcome: '歡迎回來',
    authGetStarted: '開始使用',
    authSignInSub: '登入您的帳戶',
    authCreateSub: '建立免費帳戶',
    authSignUp: '註冊',
    authLogIn: '登入',
    authContinueGoogle: '使用 Google 繼續',
    authComingSoon: '即將推出',
    authOr: '或',
    authName: '姓名',
    authNamePlaceholder: '您的姓名',
    authEmail: '電子郵件',
    authEmailPlaceholder: 'you@example.com',
    authPassword: '密碼',
    authPasswordPlaceholder: '至少 8 個字元',
    authPasswordPlaceholderLogin: '您的密碼',
    authPleaseWait: '請稍候…',
    authCreateAccount: '建立帳戶',
    authNoAccount: '還沒有帳戶？',
    authHaveAccount: '已經有帳戶？',
    // ── Schedule ────────────────────────────────────────────────────────
    scheduleTitle: '排程',
    scheduleEmpty: '尚無排程',
    scheduleEmptySub: '新增補充品到藥箱以產生排程',
    scheduleGoToCabinet: '前往藥箱',
    slotMorning: '早上',
    slotAfternoon: '下午',
    slotEvening: '傍晚',
    slotNight: '晚上',
    slotAnytime: '任何時候',
    // ── Journal ─────────────────────────────────────────────────────────
    journalTitle: '日誌',
    journalSub: '每日記錄您的感受',
    journalLogToday: '記錄今天',
    journalMood: '心情',
    journalEnergy: '精力',
    journalNotesPlaceholder: '您今天感覺如何？',
    journalSubmit: '記錄',
    journalSave: '儲存',
    journalNoEntries: '尚無記錄',
    journalNoEntriesSub: '在上方記錄第一筆以開始',
    journalDeleteConfirm: '確定要刪除此記錄？',
    journalDelete: '刪除',
    // ── Side Effects ────────────────────────────────────────────────────
    sideEffectsTitle: '副作用',
    sideEffectsSub: '追蹤補充品對您的影響',
    sideEffectsLog: '記錄副作用',
    sideEffectsSupplement: '補充品',
    sideEffectsSelectSupp: '選擇補充品…',
    sideEffectsSuppPlaceholder: '補充品名稱',
    sideEffectsWhat: '您注意到什麼？',
    sideEffectsWhatPlaceholder: '您注意到什麼？',
    sideEffectsSeverity: '嚴重程度',
    sideEffectsMild: '輕微',
    sideEffectsModerate: '中等',
    sideEffectsSevere: '嚴重',
    sideEffectsDate: '日期',
    sideEffectsSubmit: '記錄',
    sideEffectsLogging: '記錄中…',
    sideEffectsHistory: '歷史記錄',
    sideEffectsEmpty: '尚無副作用記錄 — 追蹤補充品對您的影響',
    sideEffectsDeleteConfirm: '確定要刪除？',
    sideEffectsYes: '是',
    sideEffectsNo: '否',
    // ── Progress ────────────────────────────────────────────────────────
    progressTitle: '進度',
    progressSub: '追蹤您的身體數據',
    progressLogStats: '記錄數據',
    progressWeight: '體重 (kg)',
    progressBodyFat: '體脂率 %',
    progressDate: '日期',
    progressNotes: '備注',
    progressOptional: '選填',
    progressLogging: '記錄中…',
    progressWeightPlaceholder: '例如 72.5',
    progressKgNow: '公斤',
    progressChange: '變化',
    progressEntries: '筆記錄',
    progressWeightTrend: '體重趨勢 (kg)',
    progressBfTrend: '體脂趨勢 (%)',
    progressAllEntries: '所有記錄',
    progressEmpty: '尚無數據 — 記錄您的第一筆測量',
    progressEmptySub: '使用上方表單開始。',
    progressBodyFatLabel: '% 體脂',
    progressWeightRequired: '體重為必填。',
    progressFailed: '記錄失敗 — 請再試一次。',
    // ── Bloodwork ───────────────────────────────────────────────────────
    bloodworkTitle: '血液檢查',
    bloodworkSub: '追蹤您的檢驗結果',
    bloodworkLogNew: '記錄新結果',
    bloodworkTestDate: '檢驗日期',
    bloodworkQuickAdd: '快速新增',
    bloodworkCustomMarker: '自訂指標',
    bloodworkUnit: '單位',
    bloodworkAdd: '新增',
    bloodworkValue: '數值',
    bloodworkSaving: '儲存中…',
    bloodworkLogResults: '記錄結果',
    bloodworkAnalysing: '分析中…',
    bloodworkGetAI: '取得 AI 解讀',
    bloodworkInterpretFailed: '解讀失敗 — 請再試一次',
    bloodworkEmpty: '尚無血液檢查記錄',
    bloodworkEmptySub: '在上方新增指標以追蹤檢驗結果',
    bloodworkInRange: '正常範圍',
    bloodworkBelow: '低於範圍',
    bloodworkAbove: '高於範圍',
    bloodworkMarker: '個指標',
    bloodworkMarkers: '個指標',
    // ── Doctor Prep ─────────────────────────────────────────────────────
    doctorPrepTitle: '醫師準備',
    doctorPrepSub: '下次就診時要問的問題',
    doctorPrepGenerating: '正在生成問題…',
    doctorPrepFailed: '無法生成問題',
    doctorPrepFailedSub: '請確認藥箱和個人資料有數據後再試。',
    doctorPrepRetry: '重試',
    doctorPrepReady: (n) => `${n} 個問題已準備好`,
    doctorPrepCopied: '已複製！',
    doctorPrepCopyAll: '複製全部',
    // ── Stack Builder ───────────────────────────────────────────────────
    stackBuilderTitle: '堆疊配方',
    stackBuilderSub: '輸入健康目標，幾秒內獲得個人化補充品推薦。',
    stackBuilderPlaceholder: '例如：更好的睡眠、增肌…',
    stackBuilderGenerate: '建立配方',
    stackBuilderGenerating: '生成中…',
    stackBuilderEmpty: '建立您的個人化配方',
    stackBuilderEmptySub: '在上方輸入健康目標 — 睡眠、精力、表現、免疫 — 我們會為您推薦合適的補充品。',
    stackBuilderLoading: '正在生成您的配方…',
    stackBuilderFailed: '無法生成推薦 — 請再試一次',
    stackBuilderRetry: '重試',
    stackBuilderInStack: '已在配方中',
    stackBuilderAdded: '已新增',
    stackBuilderAddToStack: '加入配方',
    stackBuilderAdding: '新增中…',
    stackBuilderEssential: '必需',
    stackBuilderBeneficial: '有益',
    stackBuilderOptional: '可選',
    // ── Notifications ───────────────────────────────────────────────────
    notificationsTitle: '通知設定',
    notificationsSub: '管理提醒、摘要和時區。',
    notificationsLoadError: '無法載入設定 — 請重新整理',
    notificationsReminders: '每日補充品提醒',
    notificationsNoReminders: '尚無提醒。在下方新增。',
    notificationsAddReminder: '新增提醒',
    notificationsDigestTitle: '每週摘要郵件',
    notificationsDigestToggle: '郵件摘要',
    notificationsDigestSub: '每週收到補充品活動摘要',
    notificationsDigestDay: '發送日',
    notificationsTimezone: '時區',
    notificationsSaved: '已儲存',
    notificationsMon: '一',
    notificationsTue: '二',
    notificationsWed: '三',
    notificationsThu: '四',
    notificationsFri: '五',
    notificationsSat: '六',
    notificationsSun: '日',
    // ── Onboarding ──────────────────────────────────────────────────────
    onboardingStep: (curr, total) => `第 ${curr} 步，共 ${total} 步`,
    onboardingGoalsTitle: '您的目標是什麼？',
    onboardingGoalsSub: '選擇所有適用的',
    onboardingGoalMuscle: '肌肉與力量',
    onboardingGoalRecovery: '恢復',
    onboardingGoalSleep: '更好的睡眠',
    onboardingGoalEnergy: '更多精力',
    onboardingGoalHealth: '整體健康',
    onboardingGoalWeight: '體重管理',
    onboardingContinue: '繼續',
    onboardingBack: '返回',
    onboardingSuppTitle: '新增第一個補充品',
    onboardingSuppSub: '之後可以在藥箱中新增更多',
    onboardingSuppName: '補充品名稱',
    onboardingSuppNamePlaceholder: '例如：肌酸、Omega-3、維生素D',
    onboardingSuppDose: '劑量',
    onboardingSuppDosePlaceholder: '例如：5g、1000mg、2顆膠囊',
    onboardingSuppTiming: '時機',
    onboardingSuppSkip: '暫時略過',
    onboardingSchedTitle: '您偏好何時服用？',
    onboardingSchedSub: '我們會根據此偏好優化您的排程',
    onboardingSchedMorning: '偏早上',
    onboardingSchedMorningSub: '中午前集中服用補充品',
    onboardingSchedEvening: '偏晚上',
    onboardingSchedEveningSub: '下午和晚上服用大部分補充品',
    onboardingFinish: '完成設定',
    // ── Evidence ────────────────────────────────────────────────────────
    evidenceStrong: '強力證據',
    evidenceGood: '良好證據',
    evidenceModerate: '中等證據',
    evidenceLimited: '有限證據',
    // ── Misc ────────────────────────────────────────────────────────────
    active: '使用中',
    conflicts: '衝突',
    interactions: '交互作用',
    failedToLoad: '載入失敗',
    suppNotFound: '找不到補充品',
    nameRequired: '名稱為必填',
    dosageRequired: '劑量為必填',
    failedToSaveChanges: '儲存失敗',
    failedToDelete: '刪除失敗',
    failedToAdd: '新增補充品失敗',
    failedToLoadHistory: '載入歷史記錄失敗',
    imageAttached: '已附加圖片',
    searchEllipsis: '搜尋或問問題…',
    msgs: '則訊息',
    messages: '則訊息',
    unknown: '未知',
    supplement: '補充品',
    // ── Relative time ───────────────────────────────────────────────────
    timeMinAgo: (n) => `${n}分鐘前`,
    timeHrAgo: (n) => `${n}小時前`,
    timeDaysAgo: (n) => `${n}天前`,
    timeYesterday: '昨天',
    back: '返回',
  },

  'zh-HK': {
    home: '主頁',
    chat: '對話',
    cabinet: '藥箱',
    profile: '個人',
    history: '歷史記錄',
    schedule: '時間表',
    stackBuilder: '配方搭配',
    doctorPrep: '醫生準備',
    sideEffects: '副作用',
    journal: '日誌',
    progress: '進度',
    goals: '目標',
    notifications: '通知設定',
    freePlan: '免費計劃',
    goodMorning: '早晨',
    goodAfternoon: '午安',
    goodEvening: '晚安',
    locale: 'zh-HK',
    statsSupplements: '補充品',
    statsConflicts: '衝突',
    statsStreak: '連續打卡',
    statsPowered: 'AI 支援',
    todaySchedule: '今日時間表',
    noScheduleYet: '未有時間表。',
    addSuppsForSchedule: '加補充品先睇到時間表',
    askAI: '問 Recallth AI',
    askAISubtitle: '我記住曬你嘅健康資料',
    askPlaceholder: '問補充品、劑量、交互作用…',
    quickPrompt1: '食D3要唔要同食物一齊食？',
    quickPrompt2: '查我嘅交互作用',
    quickPrompt3: '鎂最好幾時食？',
    recentConversations: '最近對話',
    noConversationsYet: '未有對話。',
    startFirstChat: '開始第一個對話',
    conversationFallback: '對話',
    viewAllConversations: '睇所有對話 →',
    cabinetTitle: '藥箱',
    addSupplement: '加補充品',
    searchPlaceholder: '搵補充品...',
    cabinetEmpty: '藥箱係空㗎。',
    cabinetEmptySub: '加你第一個補充品。',
    noResults: '搵唔到符合嘅補充品。',
    recent: '最近',
    interactionWarning: (n) => `你嘅藥箱有 ${n} 個交互作用`,
    addTitle: '加補充品',
    addSubtitle: '追蹤新項目',
    addButton: '加入藥箱',
    adding: '加緊...',
    editButton: '編輯',
    saveButton: '儲存',
    saving: '儲存緊...',
    cancelButton: '取消',
    deleteButton: '刪除補充品',
    deleting: '刪緊...',
    confirmDelete: '確定要刪除呢個補充品？',
    cannotUndo: '呢個操作係冇得返轉頭㗎。',
    fieldName: '名稱',
    fieldType: '類型',
    fieldDosage: '劑量',
    fieldFrequency: '頻率',
    fieldTiming: '時機',
    fieldBrand: '品牌（可選）',
    fieldNotes: '備注（可選）',
    fieldDescription: '描述',
    fieldIngredients: '成份',
    uploadPhoto: '上傳相片',
    changePhoto: '換相片',
    uploading: '上傳緊...',
    imageTooLarge: '相片要細過 2MB',
    aiLookupButton: 'AI 自動填寫產品資料',
    aiLookupTitle: 'AI 產品搜尋',
    aiLookupHint: '打個產品名（例如「PVL Whey Gold 朱古力味」），AI 會幫你填晒所有資料。',
    aiLookupPlaceholder: '例如 NOW Foods 鎂 400mg',
    aiLookupSearch: '搜尋',
    aiLookupSearching: '搵緊...',
    aiLookupClear: '清除',
    aiLookupConfirmTitle: '係咪呢隻產品？',
    aiLookupConfirm: '確認填入',
    aiLookupRetry: '再搵過',
    aiLookupFilled: 'AI 已幫你填咗產品資料',
    aiLookupUndo: '復原',
    historyTitle: '歷史記錄',
    historySub: (n) => `${n} 個對話`,
    noConversationsTitle: '未有對話',
    startConversation: '開始對話',
    noConversationsMatch: '搵唔到符合嘅對話。',
    searchConversations: '搵對話...',
    chatGreeting: (name) => `${name} 👋`,
    goodMorningGreet: '早晨',
    newChat: '新對話',
    tapSuggestion: '撳建議或者問任何野...',
    stackReview: '堆疊審查',
    todayPlan: '今日計劃',
    chatTitle: 'Recallth AI',
    chatHeaderActive: '對話',
    chatHowCanHelp: '今日有咩可以幫到你？',
    chatSugg1: '我今日嘅補充品',
    chatSugg2: '有冇交互作用？',
    chatSugg3: '最佳服用時間',
    chatSugg4: '健身前計劃',
    chatSugg5: '助眠補充品',
    chatSugg6: '科學證據',
    chatRecent: '最近',
    chatViewAll: '睇晒全部',
    chatConversations: '對話記錄',
    chatSearch: '搜尋...',
    chatNoConvos: '暫時冇對話',
    chatNoMatches: '搵唔到',
    chatFollowUp: '繼續問...',
    chatAskAnything: '問任何關於補充品嘅問題...',
    chatSentImage: '已傳送圖片',
    chatImagePrompt: '呢個係咩補充品？',
    chatNoResponse: '冇回應',
    chatError: '出咗錯，請再試過。',
    chatQuickActions: '快捷操作',
    chatJustNow: '啱啱',
    chatYesterday: '尋日',
    aboutMe: '關於我',
    goalsSection: '目標',
    exerciseSection: '運動',
    dietSection: '飲食',
    sleepSection: '睡眠',
    lifestyleSection: '生活方式',
    savingEllipsis: '儲存緊…',
    failedToSave: '儲存失敗 — 再試一次',
    profileHistory: '歷史記錄',
    profileSchedule: '時間表',
    profileDashboard: '主頁',
    fieldAge: '年齡',
    fieldHeight: '身高',
    fieldWeight: '體重',
    fieldGender: '性別',
    fieldPrimaryGoal: '主要目標',
    fieldGoalsList: '目標（以逗號分隔）',
    fieldFitnessLevel: '健身水平',
    fieldRestrictions: '飲食限制（以逗號分隔）',
    fieldAllergies: '敏感症（以逗號分隔）',
    fieldHoursPerNight: '每晚睡眠時數',
    fieldIssues: '睡眠問題（以逗號分隔）',
    fieldStressLevel: '壓力程度',
    fieldSmokingStatus: '吸煙狀況',
    fieldAlcohol: '飲酒情況',
    language: '語言',
    logOut: '登出',
    goalsSubtitle: '追蹤你每週嘅健康目標',
    goalsLogTitle: '記錄本週',
    goalsNameLabel: '目標名稱',
    goalsNamePlaceholder: '例如：瞓好啲、精力多啲',
    goalsRatingLabel: '今週表現點？',
    goalsSubmit: '記錄本週',
    goalsSubmitting: '記錄緊…',
    goalsNudgeTitle: 'AI 建議',
    goalsEmpty: '喺上面記錄你第一次每週打卡，開始追蹤',
    goalsTrend: '對比上週',
    goalsWeeks: '近 8 週',
    goalsNameRequired: '請輸入目標名稱',
    goalsRatingRequired: '請揀評分',
    goalsSubmitError: '記錄失敗 — 請再試一次',
    // ── Auth ────────────────────────────────────────────────────────────
    authWelcome: '歡迎返嚟',
    authGetStarted: '開始用',
    authSignInSub: '登入你嘅帳戶',
    authCreateSub: '建立免費帳戶',
    authSignUp: '註冊',
    authLogIn: '登入',
    authContinueGoogle: '用 Google 繼續',
    authComingSoon: '即將推出',
    authOr: '或',
    authName: '名',
    authNamePlaceholder: '你嘅名',
    authEmail: '電郵',
    authEmailPlaceholder: 'you@example.com',
    authPassword: '密碼',
    authPasswordPlaceholder: '至少 8 個字',
    authPasswordPlaceholderLogin: '你嘅密碼',
    authPleaseWait: '等等…',
    authCreateAccount: '建立帳戶',
    authNoAccount: '未有帳戶？',
    authHaveAccount: '已經有帳戶？',
    // ── Schedule ────────────────────────────────────────────────────────
    scheduleTitle: '時間表',
    scheduleEmpty: '未有時間表',
    scheduleEmptySub: '加補充品入藥箱先有時間表',
    scheduleGoToCabinet: '去藥箱',
    slotMorning: '朝早',
    slotAfternoon: '下晝',
    slotEvening: '傍晚',
    slotNight: '夜晚',
    slotAnytime: '任何時候',
    // ── Journal ─────────────────────────────────────────────────────────
    journalTitle: '日誌',
    journalSub: '每日記錄你嘅感受',
    journalLogToday: '記錄今日',
    journalMood: '心情',
    journalEnergy: '精力',
    journalNotesPlaceholder: '你今日感覺點？',
    journalSubmit: '記錄',
    journalSave: '儲存',
    journalNoEntries: '未有記錄',
    journalNoEntriesSub: '喺上面記錄第一筆開始',
    journalDeleteConfirm: '確定要刪除呢筆記錄？',
    journalDelete: '刪除',
    // ── Side Effects ────────────────────────────────────────────────────
    sideEffectsTitle: '副作用',
    sideEffectsSub: '追蹤補充品對你嘅影響',
    sideEffectsLog: '記錄副作用',
    sideEffectsSupplement: '補充品',
    sideEffectsSelectSupp: '揀補充品…',
    sideEffectsSuppPlaceholder: '補充品名',
    sideEffectsWhat: '你留意到啲咩？',
    sideEffectsWhatPlaceholder: '你留意到啲咩？',
    sideEffectsSeverity: '嚴重程度',
    sideEffectsMild: '輕微',
    sideEffectsModerate: '中等',
    sideEffectsSevere: '嚴重',
    sideEffectsDate: '日期',
    sideEffectsSubmit: '記錄',
    sideEffectsLogging: '記錄緊…',
    sideEffectsHistory: '歷史記錄',
    sideEffectsEmpty: '未有副作用記錄 — 追蹤補充品對你嘅影響',
    sideEffectsDeleteConfirm: '確定要刪？',
    sideEffectsYes: '係',
    sideEffectsNo: '唔係',
    // ── Progress ────────────────────────────────────────────────────────
    progressTitle: '進度',
    progressSub: '追蹤你嘅身體數據',
    progressLogStats: '記錄數據',
    progressWeight: '體重 (kg)',
    progressBodyFat: '體脂率 %',
    progressDate: '日期',
    progressNotes: '備注',
    progressOptional: '可選',
    progressLogging: '記錄緊…',
    progressWeightPlaceholder: '例如 72.5',
    progressKgNow: '公斤',
    progressChange: '變化',
    progressEntries: '筆記錄',
    progressWeightTrend: '體重趨勢 (kg)',
    progressBfTrend: '體脂趨勢 (%)',
    progressAllEntries: '所有記錄',
    progressEmpty: '未有數據 — 記錄你第一筆量度',
    progressEmptySub: '用上面嘅表格開始。',
    progressBodyFatLabel: '% 體脂',
    progressWeightRequired: '體重必填。',
    progressFailed: '記錄失敗 — 再試一次。',
    // ── Bloodwork ───────────────────────────────────────────────────────
    bloodworkTitle: '驗血報告',
    bloodworkSub: '追蹤你嘅檢驗結果',
    bloodworkLogNew: '記錄新結果',
    bloodworkTestDate: '檢驗日期',
    bloodworkQuickAdd: '快速加',
    bloodworkCustomMarker: '自訂指標',
    bloodworkUnit: '單位',
    bloodworkAdd: '加',
    bloodworkValue: '數值',
    bloodworkSaving: '儲存緊…',
    bloodworkLogResults: '記錄結果',
    bloodworkAnalysing: '分析緊…',
    bloodworkGetAI: '攞 AI 解讀',
    bloodworkInterpretFailed: '解讀失敗 — 再試一次',
    bloodworkEmpty: '未有驗血記錄',
    bloodworkEmptySub: '喺上面加指標嚟追蹤檢驗結果',
    bloodworkInRange: '正常範圍',
    bloodworkBelow: '低過範圍',
    bloodworkAbove: '高過範圍',
    bloodworkMarker: '個指標',
    bloodworkMarkers: '個指標',
    // ── Doctor Prep ─────────────────────────────────────────────────────
    doctorPrepTitle: '醫生準備',
    doctorPrepSub: '下次睇醫生時要問嘅問題',
    doctorPrepGenerating: '生成緊問題…',
    doctorPrepFailed: '生成唔到問題',
    doctorPrepFailedSub: '確認藥箱同個人資料有數據先再試。',
    doctorPrepRetry: '重試',
    doctorPrepReady: (n) => `${n} 條問題準備好`,
    doctorPrepCopied: '已複製！',
    doctorPrepCopyAll: '複製全部',
    // ── Stack Builder ───────────────────────────────────────────────────
    stackBuilderTitle: '配方搭配',
    stackBuilderSub: '輸入健康目標，幾秒內攞到個人化補充品推薦。',
    stackBuilderPlaceholder: '例如：瞓好啲、增肌…',
    stackBuilderGenerate: '建立配方',
    stackBuilderGenerating: '生成緊…',
    stackBuilderEmpty: '建立你嘅個人化配方',
    stackBuilderEmptySub: '喺上面輸入健康目標 — 瞓覺、精力、表現、免疫 — 我哋會推薦啱你嘅補充品。',
    stackBuilderLoading: '生成緊你嘅配方…',
    stackBuilderFailed: '生成唔到推薦 — 再試一次',
    stackBuilderRetry: '重試',
    stackBuilderInStack: '已經喺配方入面',
    stackBuilderAdded: '已加',
    stackBuilderAddToStack: '加入配方',
    stackBuilderAdding: '加緊…',
    stackBuilderEssential: '必需',
    stackBuilderBeneficial: '有益',
    stackBuilderOptional: '可選',
    // ── Notifications ───────────────────────────────────────────────────
    notificationsTitle: '通知設定',
    notificationsSub: '管理提醒、摘要同時區。',
    notificationsLoadError: '載入唔到設定 — 重新整理試下',
    notificationsReminders: '每日補充品提醒',
    notificationsNoReminders: '未有提醒。喺下面加。',
    notificationsAddReminder: '加提醒',
    notificationsDigestTitle: '每週摘要電郵',
    notificationsDigestToggle: '電郵摘要',
    notificationsDigestSub: '每週收到補充品活動摘要',
    notificationsDigestDay: '幾時寄',
    notificationsTimezone: '時區',
    notificationsSaved: '已儲存',
    notificationsMon: '一',
    notificationsTue: '二',
    notificationsWed: '三',
    notificationsThu: '四',
    notificationsFri: '五',
    notificationsSat: '六',
    notificationsSun: '日',
    // ── Onboarding ──────────────────────────────────────────────────────
    onboardingStep: (curr, total) => `第 ${curr} 步，共 ${total} 步`,
    onboardingGoalsTitle: '你嘅目標係咩？',
    onboardingGoalsSub: '揀晒所有啱嘅',
    onboardingGoalMuscle: '肌肉同力量',
    onboardingGoalRecovery: '恢復',
    onboardingGoalSleep: '瞓好啲',
    onboardingGoalEnergy: '精力多啲',
    onboardingGoalHealth: '整體健康',
    onboardingGoalWeight: '體重管理',
    onboardingContinue: '繼續',
    onboardingBack: '返回',
    onboardingSuppTitle: '加你第一個補充品',
    onboardingSuppSub: '之後可以喺藥箱加多啲',
    onboardingSuppName: '補充品名',
    onboardingSuppNamePlaceholder: '例如：肌酸、Omega-3、維他命D',
    onboardingSuppDose: '劑量',
    onboardingSuppDosePlaceholder: '例如：5g、1000mg、2粒膠囊',
    onboardingSuppTiming: '時機',
    onboardingSuppSkip: '暫時略過',
    onboardingSchedTitle: '你鐘意幾時食？',
    onboardingSchedSub: '我哋會根據呢個偏好優化你嘅時間表',
    onboardingSchedMorning: '偏朝早',
    onboardingSchedMorningSub: '中午前集中食補充品',
    onboardingSchedEvening: '偏夜晚',
    onboardingSchedEveningSub: '下晝同夜晚食大部分補充品',
    onboardingFinish: '完成設定',
    // ── Evidence ────────────────────────────────────────────────────────
    evidenceStrong: '強力證據',
    evidenceGood: '良好證據',
    evidenceModerate: '中等證據',
    evidenceLimited: '有限證據',
    // ── Misc ────────────────────────────────────────────────────────────
    active: '使用中',
    conflicts: '衝突',
    interactions: '交互作用',
    failedToLoad: '載入失敗',
    suppNotFound: '搵唔到補充品',
    nameRequired: '名稱必填',
    dosageRequired: '劑量必填',
    failedToSaveChanges: '儲存失敗',
    failedToDelete: '刪除失敗',
    failedToAdd: '加補充品失敗',
    failedToLoadHistory: '載入歷史記錄失敗',
    imageAttached: '已附圖片',
    searchEllipsis: '搜尋或問問題…',
    msgs: '則訊息',
    messages: '則訊息',
    unknown: '未知',
    supplement: '補充品',
    // ── Relative time ───────────────────────────────────────────────────
    timeMinAgo: (n) => `${n}分鐘前`,
    timeHrAgo: (n) => `${n}個鐘前`,
    timeDaysAgo: (n) => `${n}日前`,
    timeYesterday: '尋日',
    back: '返回',
  },
}

const LanguageContext = createContext()

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }
  return context
}

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState('en')

  useEffect(() => {
    const saved = localStorage.getItem('recallth_language')
    if (saved && TRANSLATIONS[saved]) {
      setLanguageState(saved)
    }
  }, [])

  const setLanguage = (lang) => {
    if (TRANSLATIONS[lang]) {
      setLanguageState(lang)
      localStorage.setItem('recallth_language', lang)
    }
  }

  const t = (key, ...args) => {
    const strings = TRANSLATIONS[language] || TRANSLATIONS.en
    const value = strings[key] ?? TRANSLATIONS.en[key] ?? key
    return typeof value === 'function' ? value(...args) : value
  }

  const getDisplayName = () => {
    const names = { en: 'English', 'zh-TW': '繁體中文', 'zh-HK': '廣東話' }
    return names[language] || 'English'
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, getDisplayName, t }}>
      {children}
    </LanguageContext.Provider>
  )
}
